### ISSUE TITLE
[BUG] Ollin Ice Cap not creating Frostbite tokens

### ISSUE THREAD

**Issue by arcabaa** [Talishar/Talishar#1054]
I defended an attack with Ollin Ice Cap and Frost Fang. Ollin Ice Cap reads 

> When this defends together with an Ice card, create a Frostbite token under the attacking hero's control.

Frost Fang is an Ice Action - Attack card, therefore when the chain resolved, the player should have gotten a Frostbite token, however, they didn't.

**Card codes**
Ollin Ice Cap: AJV004
Frost Fang: ELE148

**Comment by Pgibby8** [comment]
Do you have a bug report ID? That usually makes it easier for us to debug since these things are usually caused by specific interactions.

**Comment by arcabaa** [comment]
> Do you have a bug report ID? That usually makes it easier for us to debug since these things are usually caused by specific interactions.

I don't. I can possibly give you the game ID it happened in if that helps?

**Comment by Pgibby8** [comment]
If you don't report the bug the game data is deleted unfortunately.  I checked the code and I don't see any reason this could have happened under ordinary circumstances, so either there were extraordinary circumstances or something like erase face was missed.
