### ISSUE TITLE
App Config Value Hardcoded Into Library

### ISSUE THREAD

**Issue by sugitime** [Talishar/Talishar#113]
https://github.com/Talishar/Talishar/blob/b651245da138de39d0f9408013dc7bdc420a3b42/includes/functions.inc.php#L214

This should probably be within a config file, for a few reasons:

1. if you need to change this value for security reasons (i.e. there was a compromise on Google's side, or if they require you to change it for any other reason)
2. I dont know how sensitive this information is, but lets assume its somewhat sensitive and put it in the config file, like where the DB u/p sit, so that it can not be uploaded into github.

**Comment by OotTheMonk** [comment]
I think I must have deleted this a while back and never closed the issue. I don't see this in the code anymore. This was from when I was experimenting with google ads but decided not to add ads to the site.
