### ISSUE TITLE
[ReactUI] Don't send Gem info/status if the card/token is not interactible.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#120]
Items that as a spectator I cannot interact with still have gem information sent over:
![image](https://user-images.githubusercontent.com/5060535/209627511-c175d521-d474-42e8-957f-01d6aebc65b1.png)

In the long poll update / frame update the BE is sending that gem is "2" (inactive)

it should be "0" or a null
![image](https://user-images.githubusercontent.com/5060535/209627596-33a393a4-48d4-40e8-815e-1320f044169e.png)

**Comment by LaustinSpayce** [comment]
Reopened as there are cases where gems are appearing in card selection windows etx

**Comment by OotTheMonk** [comment]
I think this got fixed from the last time we talked, lmk if there are still cases where it's an issue
