### ISSUE TITLE
[ReactUI] Arrows in arsenal are not playable

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#137]
Backend is not sending playable card info in some cases to the FE, when the card in arsenal is an arrow (like the Man Sant stream recently)

https://github.com/Talishar/Talishar-FE/issues/51

Old FE:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/5060535/210791616-b9542661-0004-40a4-b0d4-4409519f5d89.png">

React FE:
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/5060535/210791712-4b1c40a3-57d0-479b-be0a-35840543b1b1.png">
(Drill shot is not playable)

GetNextTurn3 API info about the player's arsenal:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/5060535/210791804-5dd0b56b-e7b7-4618-bdc6-eea2c37f2efc.png">

```
{
	"playerArse": [
		{
			"cardNumber": "DYN158",
			"action": 0,
			"borderColor": 0,
			"actionDataOverride": "0",
			"controller": "1",
			"restriction": "",
			"countersMap": {}
		}
	]
}
```

**Comment by LaustinSpayce** [comment]
Somewhere in lines 391-405 in GetNextTurn3.php I think, not sure tbh:
```php
  // what's up my arse
  $myArse = array();
  if ($myArsenal != "") {
    for ($i = 0; $i < count($myArsenal); $i += ArsenalPieces()) {
      if ($playerID == 3 && $myArsenal[$i + 1] != "UP") {
        array_push($myArse, JSONRenderedCard(cardNumber: $MyCardBack, controller: 2));
      } else {
        if ($playerID == $currentPlayer) $playable = $turn[0] == "ARS" || IsPlayable($myArsenal[$i], $turn[0], "HAND", -1, $restriction) || ($actionType == 16 && strpos("," . $turn[2] . ",", "," . $i . ",") !== false);
        else $playable = false;
        $border = CardBorderColor($myArsenal[$i], "HAND", $playable);
        $actionTypeOut = (($currentPlayer == $playerID) && $playable == 1 ? 5 : 0);
        if ($restriction != "") $restriction = implode("_", explode(" ", $restriction));
        $actionDataOverride = (($actionType == 16 || $actionType == 27) ? strval($i) : "");
        array_push($myArse, JSONRenderedCard(cardNumber: $myArsenal[$i], action: $actionTypeOut, borderColor: $border, actionDataOverride: $actionDataOverride, controller: $playerID, restriction: $restriction));
      }
    }
  }
  $response->playerArse = $myArse;
  ```

**Comment by OotTheMonk** [comment]
![image](https://user-images.githubusercontent.com/77394768/210899684-cfedb62c-919e-4f13-8ed0-b19bd7a6e4dd.png)
Fixed in this commit, don't know why it's not letting me attack it discretely
