### ISSUE TITLE
Require player validation for chat.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#138]
Spectators can chat if they're naughty and make requests for chat manually. Like I did:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/5060535/210811157-913758a7-b209-4782-9ec7-452e3ad383ee.png">

<img width="411" alt="image" src="https://user-images.githubusercontent.com/5060535/210811742-50dd47c6-a2ad-40bb-b2d0-0d237dafddfa.png">

Sample game where I terrorised the players by talking in chat:
484273

I disable on the FE but we need it validated on BE because people will be naughty.

**Comment by OotTheMonk** [comment]
Fixed by fab5a738 and 522d3a30

**Comment by LaustinSpayce** [comment]
OK so you've also fixed the cross-subdomain session? Because chat will then be completely broken without it in the new react FE. Also depends on https://github.com/Talishar/Talishar/issues/145 being fixed.
