### ISSUE TITLE
Password not required for updating profile

### ISSUE THREAD

**Issue by sugitime** [Talishar/Talishar#141]
https://github.com/Talishar/Talishar/blob/0b40f2677e29ca2666597b8befb6b3fe41893f26/profile.php#L13

The user's password should be requires for updating profile settings to prevent CSRF attacks. As an example, an attacker can send a link to a victim which leads to an auto-submitting form that updates the user's username. Once this is completed, the attacker can take over the victim's username by editing their own account. Because some functionality is tied to username verification in lieu of more complex ACL's, the a user's username is more sensitive.

requiring the password be re-entered prevents an attacker from performing this attack.

**Comment by OotTheMonk** [comment]
Fixed by deleting the account editing functionality entirely
