### ISSUE TITLE
End Game Stats needs to send card name + pitch

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#142]
The end game stats sends just the card number for the card stats, which is great for a picture of the card, but the FE has no way to lookup the name of a card from just, say "ARC010".

I can import a dictionary of card names etc into the FE (I will have to do this eventually anyway) but in the meantime this would be very nice to have.

**Comment by OotTheMonk** [comment]
Fixed by revision 1545874a
