### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by sugitime** [Talishar/Talishar#147]
https://github.com/Talishar/Talishar/blob/a0449a24262c926695357e623cc503d11a2c3101/includes/functions.inc.php#L195

This is vulnerable to SQL injection. It needs to use the ? placeholder instead of $token in the $sql variable. It should look like the following:

`$sql = "SELECT usersID, usersUid, usersEmail, patreonAccessToken, patreonRefreshToken, usersKarma, patreonEnum FROM users WHERE rememberMeToken=?";
	$stmt = mysqli_stmt_init($conn);
	if (mysqli_stmt_prepare($stmt, $sql)) {
                mysqli_stmt_bind_param($stmt, "s", $token);
		mysqli_stmt_execute($stmt);`

Here are locations where similar changes need to be made:

https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/includes/reset-password.inc.php#L24
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzPlayerHeroStats.php#L62
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzPlayerHeroStats.php#L76
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzPlayerHeroStats.php#L88
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzPlayerHeroStats.php#L101
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzHeroStats.php#L60
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzHeroStats.php#L74
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzHeroStats.php#L86
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzHeroStats.php#L99
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzMatchupStats.php#L58
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzMatchupStats.php#L71
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzMatchupStats.php#L83
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzMatchupStats.php#L83
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzPatreonDebug.php#L24
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/zzGameStats.php#L94
https://github.com/Talishar/Talishar/blob/ec290ffd1e0db19c4b683512cbe687582b62f01b/MenuFiles/DeleteDeck.php#L12

**Comment by OotTheMonk** [comment]
I fixed a lot of these, except the zz ones, which should already all be locked down to mods. Still should probably fix them though so I'm leaving the ticket open. Lots of commits starting with c16c84f6

**Comment by OotTheMonk** [comment]
Fixed the zz ones unfixed from yesterday; closing issue as fixed. Let me know if I missed any!
