### ISSUE TITLE
[ReactUI] more events to show in nice toasts on the fe

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#152]
We have hot toast being served up in the react front end. And we need events to serve!

starting point:

- Die rolls (implemented!)
- Cards revealed (for fuse! For Kano! For boost! For ravenous rabble! For anything you show your top deck for! For cards banished from graveyard so your heart can sink when you have 15 blood debt and it banishes the only three non 6 power cards from your gy!)
- Cards discarded!
- Cards banished! (From hand and from gy and deck I guess)
- we might need an “eventResultArray” in the response/json if we wanna reveal multiple cards being banished in one game action.
- Anything else that can be suggested.

**Comment by OotTheMonk** [comment]
Reveal banish and soul were added in the last commit, looks like only discard is left of the proposed ones

**Comment by OotTheMonk** [comment]
Added discard in 7e27c483. I believe events are already in an array. If we have more ideas of events to add we can open new issues.
