### ISSUE TITLE
Can you sort the matchup list alphabetically and make it scrollable?

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#153]
https://discord.com/channels/865412150125789214/971928581267664936/1062226640626790400

In this line add `overflow: scroll`. (done ✅)
https://github.com/Talishar/Talishar/blob/59689470b6021389cff5097cdea3bc882dde3dfa/GameLobby.php#L209

> When you pull the matchups from fabrary you must just render them in the order they come from their API. Just throw a usort on that array to sort by name before rendering the html.

Can add the sort before this line perhaps.
https://github.com/Talishar/Talishar/blob/59689470b6021389cff5097cdea3bc882dde3dfa/GameLobby.php#L216

**Comment by LaustinSpayce** [comment]
overflow-y: scroll done.

Just need a sort if we want it.

**Comment by OotTheMonk** [comment]
I believe this is fixed by commits 3d0f7709 and f8854ab7
