### ISSUE TITLE
[ReactUI] Set and Retrieve a Playmat as an option.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#160]
We need to be able to set a playmat.

Actual playmats TBC, we should try and get some artwork, or at least some nice colour textures.

We need to be able to get a playmat somewhere in the game response. I think it needs to be part of GetNextTurn3 as it needs to be loaded in immediately.

Later on we can have some fancy on-load special request that's only called once.

**Comment by OotTheMonk** [comment]
Right now it's a little wonky, but the playmat is controlled by the $SET_DarkMode setting.
0 is a light mat, 1 is a dark mat, 2 is a "plain" light mat, 3 is a "plain" dark mat

Were you thinking adding a new setting? Like the card back one?

**Comment by LaustinSpayce** [comment]
Yes, the player customisable ones. I would have a playmat and so would the opponent. We would control a list of available playmats (not allow everyone to upload whatever they want for weeb central)

**Comment by LaustinSpayce** [comment]
So this is different to the game scene which is what you currently have (which is an individual player preference)

I'd deprecate the SET_Darkmode and we can see what the best way to implement it in the react UI is.

**Comment by OotTheMonk** [comment]
This is fixed :)
