### ISSUE TITLE
[ReactUI] update link to new UI to open in same window as opposed to a new window.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#162]
Now the great cookie conundrum has been resolved, the options menu link "Open beta UI in new window" should open in the same window and not a new window.

And we can remove "in new window" i guess unless we wanna confuse people.

And move the button toward the top of the menu so it's more obvious.
And looks like the UI proper rather than some crummy link I half-bothered to put in.

**Comment by OotTheMonk** [comment]
Fixed in be0298c3
