### ISSUE TITLE
[ReactUI] End point for rematch, vote up / vote down etc.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#164]
I need to know what the APIs are for all of the end-game content are. Because I need to have it that people can thumbs up / thumbs down, rematch, quick rematch etc from the end-game screen on the react client.

**Comment by OotTheMonk** [comment]
Those actions all go through the same ProcessInput2 entry point. (I believe that none of these have special parameters that need to be passed in)
Quick Rematch: 100000
Navigate to main menu: 100001
Concede: 100002
Report Bug: 100003
Full Rematch: 100004
Green thumb: 100008
Red thumb: 100009
Resume adventure (if it's a roguelike game): 100011
Create Replay (if applicable): 100012
