### ISSUE TITLE
Cash in / CLF Frostbite bug

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#168]
Apparantly reported multiple times on the discord, so leaving an issue about it here to be addressed ASAP.

https://twitter.com/PvtVoid/status/1614498717192650752?s=20&t=UaXrj7xanLkrjgD7b9hfGA

**Comment by OotTheMonk** [comment]
Fixed in c1180715

**Comment by PvtVoid** [comment]
Is this issue only for Cash In? Or for all alternate cost? 

The issue has been fixed for Cash In, but is still present on other cards. For example (Game ID 557739) playing Staunch Response with 4+ Frostbite will give Staunch a defense bonus.

Feel free to close it again if this was an issue only for Cash In

**Comment by LaustinSpayce** [comment]
The scope of this specific fix @PvtVoid was just for cash in. If there’s a larger issue surrounding all alternate and additional costs can you please make an issue for those?
