### ISSUE TITLE
Emperor doing CNC ability does not destroy arsenal

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar#176]
The reason is because the attack target is not populated

**Comment by OotTheMonk** [comment]
This worked when I tried it

**Comment by OotTheMonk** [comment]
It looks like this might happen when the target is prism, who has a spectra out:
![image](https://user-images.githubusercontent.com/77394768/217975945-3add0020-043e-49b5-9952-9d6f26550649.png)

Game reference: 721817

**Comment by KuKetto** [comment]
I will look into this issue. This issue expends as:
- You are not allowed to choose Command and Conquers attack target (enemy hero is automatically targeted) however you should be able to. 
_When you activate Emperor, it is considered an attack and requires you to specify the attack target._ 
- With one angel (ward 4) the same issue came up (opponent's arsenal isn't destroyed)

**Comment by KuKetto** [comment]
Cause:
- Recursive decision queue, the attack target selection is skipped so CNC literally targets itself.

There is a fix on this [commit](https://github.com/Talishar/Talishar/commit/6a598c145df4e92ba2b5031fb19a29affdec3243) however there should be a better way to fix that. @OotTheMonk please check it in your free time

**Comment by PvtVoid** [comment]
Fixed with https://github.com/Talishar/Talishar/pull/716/commits/a557b6d341fdd6083e6a933c409e3861496e557e
