### ISSUE TITLE
Issues with alternative costs, additional costs; and CLF and Frostbites.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#180]
Is this issue only for Cash In? Or for all alternate cost? 

The issue has been fixed for Cash In, but is still present on other cards. For example (Game ID 557739) playing Staunch Response with 4+ Frostbite will give Staunch a defense bonus.

_Originally posted by @PvtVoid in https://github.com/Talishar/Talishar/issues/168#issuecomment-1384342225_

Let’s evaluate about how best to tackle, seems the whole system surrounding alternate costs and CLF / frostbites is buggy.

**Comment by LaustinSpayce** [comment]
If other people report things like this let’s include their reports here

**Comment by OotTheMonk** [comment]
This is an issue with the variable/additional cost cards. (for example Sonata and other X cards likely also affected.

**Comment by OotTheMonk** [comment]
Actually I tested this with sonata, and it is NOT affected.

**Comment by OotTheMonk** [comment]
Fixed by 77f26451
