### ISSUE TITLE
[Talishar 2.0] - secrets management

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#195]
We need to manage our api keys, they cannot be checked into the server, we need to use env variables. Some system similar to dotENV or whatever.

I accidentally committed an api key I was used for testing to the repo. And now I have to go through the process of asking the api owner to revoke that key and issue a new one, it’s just very amateurish and very easy for us to completely bone it up on occasion.

For us active collaborators we have a one password teams account. so we should be leveraging OP to manage secrets for us through the secrets automation features it has so this doesn’t happen again!

**Comment by OotTheMonk** [comment]
Did you already fix this in revision 25e46fca?

**Comment by LaustinSpayce** [comment]
It's only a partial fix for this one specific use case. What about for everything else like the db, redis, other stuff I don't know about and etc?

**Comment by OotTheMonk** [comment]
I think this is fairly well resolved in the short term, with the additional caveat that we should just not rely on putting newly added keys in plaintext files anymore. Closing this one for now since there's not anything clearly actionable.
