### ISSUE TITLE
POST requests for user authentication

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#198]
I need api end points for react api to call that do the following:

POST
login - I give you username and password and you give me the auth cookie and stuff to validate everything else 
reset password - emails them the reset password link
Set new password from email link
Change password - from their profile,page 

GET
user information: username, decks, deck stats etc.

POST/DELETE
Delete a deck from their favourites / profile (user has decks so it’s part of this flow)

**Comment by OotTheMonk** [comment]
Try Login from cookie + get login status API in revision f3919fb1
Postman test: Try Login API

**Comment by OotTheMonk** [comment]
Password login API in revision 2471adf2
Postman test = Password Login

**Comment by OotTheMonk** [comment]
Logout API in revision 33033832
Postman test = Logout API

**Comment by OotTheMonk** [comment]
Password reset request API revision ce23cb82
Postman test = Password Reset Request

**Comment by OotTheMonk** [comment]
I think getting the user name should be covered in the TryLogin API, and getting the deck info should be covered by APIs/GetFavoriteDecks.php. I'm not sure what is meant by deck stats; we don't store any deck stats in talishar. That's all stored by fabrary/fabdb.

Still todo:
1. Change password (from the email)
2. Delete deck

**Comment by OotTheMonk** [comment]
Delete deck API revisions 2df25de2 and 4e5bf843 (hooray for testing)
Postman test = Delete Deck

**Comment by OotTheMonk** [comment]
Added reset password API in e4c81f55

Also added postman test:
![image](https://user-images.githubusercontent.com/77394768/218324421-690ab50e-1519-46f8-b3a5-2ee177a9b70c.png)

NOTE: If you want to use the postman test, you need to use the other postman APIs (or the normal UI) to send the password request email. You'll need to copy and paste the parameters from the email link into the parameters of the postman API.

WARNING: This WILL reset your password. Make sure you use a test email/account if you don't want to mess up the password on your main account.

I believe this is all the login APIs from the OP. Let me know if any others are missing :)
