### ISSUE TITLE
API end points for starting a game

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#199]
POST - with settings
- HostLobby - deck, description, format etc. same as current.
- Joinlobby - deck, description, format etc. same as current.
- SubmitDeck- submit the deck before playing, so the response is either an ok or an error saying what is needed to be fixed.
- Go first or second - allow player to choose
- Ready - ready up button

Queries - GET
- get active game lobbies - same as front page, include for spectate the format too
- Get deck by format. A users favourite blitz decks eg. (Could probably just include as getdecks?format=blitz eg
- Get user information all game and stats info as profile screen
- Get deck - I need a list of all the cards and what equipment or weapon slot they go into, and validation if the weapon is 1 or 2 handed etc.
- Long poll query for sideboarding screen.

**Comment by OotTheMonk** [comment]
Game list api: 5b731050

**Comment by OotTheMonk** [comment]
Favorite Decks API: 8a8ab88f

**Comment by OotTheMonk** [comment]
Profile API minus stats: 75703812

**Comment by OotTheMonk** [comment]
Get deck (GetLobbyInfo) - Revision dc79e391

**Comment by OotTheMonk** [comment]
Get lobby refresh - Revision 133c46f4

**Comment by OotTheMonk** [comment]
Create and join game API - Revision aa6b301e

**Comment by OotTheMonk** [comment]
Choose first player api - Revision 7c854119

**Comment by OotTheMonk** [comment]
Submit sideboard API fcdce7ec

**Comment by OotTheMonk** [comment]
Submitting the sideboard counts as readying up
