### ISSUE TITLE
Single Fuse sometimes makes the fuse window get skipped

### ISSUE THREAD

**Issue by Etasus** [Talishar/Talishar#205]
Sometimes, whenever a fuse card is attempted to be played, the window to reveal a card to fuse is skipped entirely

**Comment by OotTheMonk** [comment]
This is an issue with this passinput executing after a card is played from hand:
![image](https://user-images.githubusercontent.com/77394768/214456803-4f6773ba-0777-400f-98a6-a3622ad027b0.png)
When the AI plays a command, the top level evaluation loop needs to be started over
