### ISSUE TITLE
Messed up display for cash in replacement effect

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#207]
BE needs to send out our {{card-in-string}} encoded format we decided on, so I can replace janky inline HTML like this with proper card names and highlights.

![3AA6DC38-8091-4584-9A5B-6DEBF0EE078D](https://user-images.githubusercontent.com/5060535/214608077-3a51f7e7-578c-4962-83ea-f7de229f5901.jpeg)

**Comment by LaustinSpayce** [comment]
Also this kind of prompt should also say - you still need to pay additional costs for frostbite etc.

**Comment by OotTheMonk** [comment]
case $SET_UseReactUI: return "0";//TODO: Change this to "1" when react UI is on by default

**Comment by OotTheMonk** [comment]
Added setting for which UI you're using: 3ba423c2

Still TODO:
1. Swap the setting when you switch UIs
2. Change the WriteLog function to write the new format when you're in the new UI

**Comment by OotTheMonk** [comment]
^Actually this whole thing won't work, because the two players might be on different UIs. We need to store off two copies of the game log. One for the react UI, one for the old UI.

**Comment by LaustinSpayce** [comment]
For the php / legacy client we might be able to use a replacement effect, detect the {{ and replace with the card info }} ? no need to save two copies.

**Comment by OotTheMonk** [comment]
This comes from the function GetDQHelpText. This basically just uses dqState[4]:
![image](https://user-images.githubusercontent.com/77394768/218909162-b7c67f9e-82b2-410b-98c4-699b800af891.png)

**Comment by OotTheMonk** [comment]
The {{}} thing is already coded out, it's just not active. For now we're going to try to render the HTML, and defer this ticket until after the react release is done. Then we won't need to worry about backwards compatibility.

**Comment by OotTheMonk** [comment]
This is working, although it would benefit from being refactored in the future. Closing as not working on now:
![image](https://user-images.githubusercontent.com/77394768/222600129-4e8cc68c-52ad-4e4d-b29c-74b8a9fb3177.png)
