### ISSUE TITLE
CounterMap should be null if empty

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#208]
Can save a bit of space by having countersmap be null if it is empty.

https://github.com/Talishar/Talishar/blob/a792a0c78739c8d8090693f715d5adf3b6f7aafb/Libraries/UILibraries2.php#L124

**Comment by OotTheMonk** [comment]
I looked into this; the logic is a little complicated. I don't think the extra logic is worth the slight size savings (and actually I think an empty object is less space in JSON ({} vs NULL)
