### ISSUE TITLE
Whirling Mist Blossom does not draw cards if buffed

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#212]
If whirling mist blossom is buffed by some effect like Art of War, it won't draw cards when it is the second or greater chain link in a row to hit.

> 640991 Bug that ira's whirling mist blossom doesnt draw cards on hit
> i think it didnt work both times after I buffed the attack with an attack reaction/instance ie. AOW and Ancestral
> 641245
> attack was double strike then whirling mist blossom and ancestral reaction to only get one card for the ancestral but not for the hit
> 641381
> actually I lie there are buff from AOW and Ira ability

https://discord.com/channels/865412150125789214/865423689976774656/1068769411969859624

**Comment by OotTheMonk** [comment]
Took a look at the bug reports, the previous chain link had not hit. Trying it normally with the previous chain link hitting draws the cards.
