### ISSUE TITLE
ReactFE APIs - player disconnecting does not reset lobby refresh status

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#234]
Anyway there's something that needs to be fixed in the APIs.
Player 1 sets up lobby
Player 2 joins
Player 2 leaves
Lobby Refresh still says Player 2 and their hero is in the lobby, chat says they have left though.

it should be replaced with something.

I would also be much happier if there’s no second player, the player2 name is blank.

also, if a player disconnects from the lobby it takes a while to register they have left. Maybe need some active api to leave a lobby.

**Comment by OotTheMonk** [comment]
Fixed in revision c5ed21f3
