### ISSUE TITLE
674335 - Lightning Press doesn't show properly as an Attack Modifier

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#238]
Lightning Press doesn't show properly as an Attack Modifier. It shows like my arrow buff itself, which isn't exact and possible with Chilling Icevein.

![image](https://user-images.githubusercontent.com/26232486/216306118-9f87569f-7af3-4b44-92f5-5eaf0367a04d.png)

**Comment by OotTheMonk** [comment]
Fixed in revision ed300b05
![image](https://user-images.githubusercontent.com/77394768/222601176-9fc9736b-0f5d-40af-bf95-c145be034616.png)
