### ISSUE TITLE
No Game ID - Temper doesn't get broken when shredded

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#243]
I haven't tested but someone reported this to me today.

"If you target a defending equipment with Temper and its {d} is reduced to 0, it will be destroyed when the combat chain closes."
Additional info: https://fabtcg.com/resources/rules-and-policy-center/release-notes/dynasty/

![image](https://user-images.githubusercontent.com/26232486/216556718-9217896c-1a24-406c-910a-57a20c3cd900.png)

**Comment by OotTheMonk** [comment]
Just tested, this is working for me. Temper doesn't check until the combat chain closes so maybe that is why? Let us know if you're able to reproduce.

![image](https://user-images.githubusercontent.com/77394768/216611663-c5aa7ad3-7b28-45ce-9ce3-909ab0746510.png)

**Comment by PvtVoid** [comment]
I just tested and it seems to work for me too. Not sure why it got reported, but I informed them that it should be working
