### ISSUE TITLE
681273 - You cannot target previous attacks with reactions

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#245]
I tried to play Singing Steelblade targeting my previous sword attack on chain link 2. So I could tutor a pummel from my deck and pummel my Nourishing Emptiness, but Talishar doesn't allow me to. Even tho it's a legal target. 

Let me know if you need more information on this interaction 🐝

**Comment by PvtVoid** [comment]
What's a FYI-BUG?

**Comment by OotTheMonk** [comment]
Not an immediate priority; adding fix later tag
