### ISSUE TITLE
687150 - [QoL] With the setting "never hold priority" it still holds priority to Runechant

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#249]
Playing Dorinthea you run into the issue that the opponent knows when you have an Ironsong Pride in hand with the "auto-hold priority" setting. So to fix that I run the Always Hold Priority, but if you have an instant in hand it seems to be back to "auto-hold priority" when there are Runechants popping. I think it makes sense if people run "auto priority" to hold it or have the tunic up. Maybe there's an easy fix?

**Comment by OotTheMonk** [comment]
Do you have a game reference number for this issue? That would let us get a better idea of what's going on. From the description alone it's not very clear how to reproduce.
