### ISSUE TITLE
ReactUI - Make sideboard submission work in any order

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#250]
There is a major bug with two players trying to join a game. They have to submit their sideboard in a specific order else it doesn't create the game properly

Also, in the `getLobbyRefresh` long poll, there is no change to the field `submitSideboard` between the two enums `'none'` and `'block'` (whatever they mean) when a player submits their sideboard.

I'd like the behaviour to change to this:
In `LobbyRefresh` have an additional field - `isMainGameReady` boolean.
We change `submitSideboard` field to be a boolean, I think we can rename it to `canSubmitSideboard`

When joining a lobby we request the die roll in LobbyPoll as it is right now.
`canSubmitSideboard = false`
Whoever wins the dice roll picks to go first or second
`canSubmitSideboard = true` for both players - I can enable the sideboard submission button then in the lobby page.

Each player can submit their sideboard whenever they want after one player picked to go first or second.

We add a field in getLobbyRefresh, like `isMainGameReady`:
When both players have submitted their sideboards and they are legal, isMainGameReady = true
I can then monitor isMainGameReady in the long poll and move the players over to the game when this is true.

The sideboards must be able to be submitted independently and in any order.
The SubmitSideboard API must be able to support a card named `NONE00` to represent "no card" - a conscientous choice to not wear arms equipment etc.
If for any reason the sideboard is illegal or not allowed I need an errorMessage returned I can display as a user inside the JSON. Not `echo "deck wrong"` please

**Comment by OotTheMonk** [comment]
Added the new properties in 33944911 and f39c657c
![image](https://user-images.githubusercontent.com/77394768/217128444-bbec71e0-2a98-4b1c-bf3e-0f509462330c.png)

I did not delete the old weird property because I wanted to upload it and stay backwards compatible; once we switch off the weird one we can delete it later.

I think it will support NONE00 as representing no card but we would need to test that to be sure.

**Comment by OotTheMonk** [comment]
Added deck validation in a72b9658

Updated already existing status variable with a FAIL when it fails
Added new deck error property with presentable text (no html formatting)

![image](https://user-images.githubusercontent.com/77394768/217129729-3701dcca-1a82-4177-9f09-4e14e8995922.png)
