### ISSUE TITLE
698644 - Reinforce the Line + defending buff/debuff aren't visible 

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#253]
2 issues:
- Reinforce the Line doesn't have a log telling the players what was targeted.
- It's impossible to know which attack action cards to target with Rout (The same issue can come up with Shred for example)

![image](https://user-images.githubusercontent.com/26232486/216953037-bb44f9b1-bca4-4fd5-94fd-3a9287d6f059.png)

**Comment by OotTheMonk** [comment]
Fixed a few different cards that can buff defense (revision 33e74250)
![image](https://user-images.githubusercontent.com/77394768/222602252-ebfe83db-f34f-43c7-82e9-bef5a0b5c29c.png)
