### ISSUE TITLE
[Bug] - Oasis respite not applying to unique copy of card

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar#256]
One oasis can prevent damage from multiple ashwings, for example

**Comment by PvtVoid** [comment]
![image](https://github.com/Talishar/Talishar/assets/26232486/45077cba-3612-42f7-b786-d58f30b39d48)

3905849 - https://discord.com/channels/865412150125789214/865423689976774656/1193634029195493528
3787009 - https://discord.com/channels/865412150125789214/865423689976774656/1188531275833815120

**Comment by PvtVoid** [comment]
New case with 2x Hot Streak attack for 2.
4057547 - https://discord.com/channels/865412150125789214/865423689976774656/1199007002488209490
