### ISSUE TITLE
706150 - Some allies (Cromai in this case) don't have a value for their pitch and it's defaulted at 3 showing them as a blue pitch

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#257]
Cromai text in the chatlog + target show in Blue as if the ally had a blue pitch. It should show as null.
`9.1.2. Each face of a double-faced card has its own set of printed properties.`

![image](https://user-images.githubusercontent.com/26232486/217247546-4390b2d1-d8dd-42b3-a983-bd63a4991809.png)

**Comment by PvtVoid** [comment]
I can confirm that I've seen it with other dragons during the game and that it doesn't affect only Cromai, but most likely all UPR400+, Nitro Mechanoid, etc...

**Comment by OotTheMonk** [comment]
Fixed
