### ISSUE TITLE
Every lobby - The background isn't centered anymore

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#260]
Firefox, the position doesn't change based on my zoom. It's fixed there.

![image](https://user-images.githubusercontent.com/26232486/217353113-e06ae3e2-55c7-48a9-adac-f10cab575035.png)

**Comment by OotTheMonk** [comment]
Closing because this screen won't exist soon

**Comment by LaustinSpayce** [comment]
There’s nothing to do here so it can’t be completed. The new UI will have a better background when it’s finished
