### ISSUE TITLE
Dissipation Shield

### ISSUE THREAD

**Issue by GabeFishandBlood** [Talishar/Talishar#263]
It does not appear dissipation shield works successfully with arcane damage

**Comment by LaustinSpayce** [comment]
Do you have a game ID or anything to help us reproduce the issue?

**Comment by OotTheMonk** [comment]
Works fine when I tried it
![image](https://user-images.githubusercontent.com/77394768/222599651-1e0948ec-d7f2-476d-88ac-7dbbfdf54892.png)
