### ISSUE TITLE
Receive warning when logging in.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#274]
Calling `PasswordLoginAPI.php` :

Receive:
```
<br />
<b>Warning</b>:  Undefined array key "usersId" in <b>/var/www/html/game/AccountFiles/AccountDatabaseAPI.php</b> on line <b>35</b><br />
{"isUserLoggedIn":true,"loggedInUserID":null,"loggedInUserName":"TestTesterson"}
```

Need the warning suppressed

**Comment by OotTheMonk** [comment]
I think this is fixed. I fixed the undefined array key issue, removed the error reporting code, and the login is working. Can check out revision b1de7b5d for reference.
