### ISSUE TITLE
Lobby game breaking bug when users are on different clients.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#276]
So I'm using the new client on my phone going to work and I imagine my opponent is on the old one. 

![image](https://user-images.githubusercontent.com/5060535/218349163-d6c46cd2-db3c-414e-b6f6-f916fb24b09c.png)

Basically the game start system breaks when people submit their sideboards out of order, across old and new clients. I will try to reproduce later today. But it's good to fix because some people prefer to stick with the old client and also for testing.

**Comment by OotTheMonk** [comment]
I changed the normal game to use the same flow where the sideboard can be submitted in either order d58586b9
