### ISSUE TITLE
Deck issue with Arakni and Spider Bites

### ISSUE THREAD

**Issue by ChrisMorris630** [Talishar/Talishar#290]
If you use FabRary.net and setup your Arakni with a Spider's Bite in the Main deck and a Spider's Bite in the Sideboard, it results in the client not recognizing you have the spider's bite in your sideboard. It also does not automatically select the spider's bite in the main board. I attached a quick screenshot from the Discord conversation I was having with both my games (first one being with 1 bite main, 1 bite side, and the second with both bites main.)
![Spiders Bite](https://user-images.githubusercontent.com/63126931/219176355-71a0d42d-d66c-4aae-90a4-d8d5ddc57409.png)

**Comment by ChrisMorris630** [comment]
https://fabrary.net/decks/01GSBG5DE6Q7NWTFFPCY0EQKBZ

This is my Fabrary link. It currently has both daggers main and I am auto selecting the tessen each time but found it an interesting bug.

**Comment by OotTheMonk** [comment]
Tried to make a copy of the deck to move one of the daggers to the SB; was able to reproduce the issue.
https://fabrary.net/decks/01GSNBJZYMEQYDV81XQX0J7N3K

Notably this deck also doesn't work entirely on the new FE. Definitely needs a fix.

**Comment by OotTheMonk** [comment]
Fixed in revision 05ddeed9
