### ISSUE TITLE
[ReactUI] cannot play arrows (with aim counters?) from Arsenal

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#297]
Azalea's arrow cards in arsenal are not being given info from the BE to make them playable, against the training dummy.

How myArsenal is reported to FE with an arrow card:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/5060535/219872635-5ca1c1a6-dc4f-467a-a73d-fc3b257c9ba9.png">

A second example:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/5060535/219872803-bc196dc9-8eb7-4a22-baee-19c8bff3e29e.png">

For some reason flipping a card off the top of your deck into Arsenal using Azalea's ability puts an aim counter on the card.

Arrows put into arsenal normally are reported as playable. Just ones with aim counters on them are not playable.

**Comment by OotTheMonk** [comment]
Were you using sandscour greatbow? If so, it's expected for it to have an aim counter on it:
![image](https://user-images.githubusercontent.com/77394768/219876454-acf5736f-d8c4-4529-a498-cc9db3b478b8.png)

(Not being able to play it is obviously not expected 😝)

**Comment by OotTheMonk** [comment]
Fixed in 559b5527. There was a problem with aim counters not rendering as well that I also fixed.

**Comment by OotTheMonk** [comment]
![image](https://user-images.githubusercontent.com/77394768/219876918-1744ac21-081a-4940-b339-f28448c33dde.png)
