### ISSUE TITLE
Sonata Arcanix issue

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#304]
Sonata arcanix cannot be played in the new FE because there’s a bug with how the checkboxes work, the be is expecting something different so we have to figure out what the be is expecting.

if this is like some special weird case because of the BE we should bring it in line in the be to everything else that is selecting multiple cards

**Comment by OotTheMonk** [comment]
Fixed in revision 98f006fb
![image](https://user-images.githubusercontent.com/77394768/220804542-49b413e7-feb9-44b0-952a-79e7dc59043e.png)
