### ISSUE TITLE
Arcane lantern is 1handed equipment

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#305]
Lots of items that are 1 handed are being reported as 2 handed so we need to fix these, as flake discovered on stream trying to equip a lantern to his old him with titans fist and it didn’t work.

**Comment by OotTheMonk** [comment]
Fixed in revision c7595bb2
![image](https://user-images.githubusercontent.com/77394768/220800995-de8d0991-23e3-47ca-b22b-b44825a29b74.png)
