### ISSUE TITLE
[react fe] blood on her hands mode selection broken

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#307]
![D9441602-2A21-4301-8CED-59CB13FFCAC5](https://user-images.githubusercontent.com/5060535/220961556-cb21c805-e53e-4f8a-a311-bdd78486dfa7.png)
![D3798795-AB35-4B03-A896-1CE583CC8D33](https://user-images.githubusercontent.com/5060535/220961585-275a209b-9368-4e92-8313-71ed9b74749d.png)

I had to switch to old client to activate it.

bohh was working fine until today so I’m sure this is a side effect of the sonata or something fix

**Comment by OotTheMonk** [comment]
Fixed in 61ec13d2 and also PR https://github.com/Talishar/Talishar-FE/pull/178
