### ISSUE TITLE
[ReactFE] Micro-processor is not greyed out after first activation (unlike Induction chamber etc)

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#315]
It can be hard to tell which micro-processor you have used if you've used more than one, when you've used it, it should be greyed out I think, like Induction Chamber, so you know you won't gain an action point from activating it a second time.

**Comment by OotTheMonk** [comment]
Fixed in revision 912b2395

Both legacy FE and react FE
