### ISSUE TITLE
864519 - When you click NO for Be Like Water it still prompt the name choice and add it in the current effects

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#328]
![image](https://user-images.githubusercontent.com/26232486/223127456-89760829-b497-4a4d-a2d3-171722c1a944.png)
![image](https://user-images.githubusercontent.com/26232486/223127475-a72412e0-6c54-4197-b6fc-72c40103a652.png)

**Comment by OotTheMonk** [comment]
Fixed in c38365ef
