### ISSUE TITLE
871112 - [Bug] Uzuri allows for buffs to carry over to the next card

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#336]
I played Uzuri first and then another reaction and it'll give the buff to the new attacking action card. I don't think it should be resolved as there's no more valid target with the next card being a different target without Stealth.

![image](https://user-images.githubusercontent.com/26232486/223364545-2fc1bde8-d49e-40da-a421-3c203ec01439.png)

**Comment by OotTheMonk** [comment]
Uzuri can no longer allow attack reaction buffs to carry over to the next card
9e91dc3c
