### ISSUE TITLE
871491 - Codex of Frailty card put in arsenal isn't "revealed"

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#341]
Because the card comes from the Graveyard (A public zone) the players should know what the other has put in the arsenal from the graveyard. Like Candlehold and other cards that are already coded like that.

![image](https://user-images.githubusercontent.com/26232486/223390728-da4bf71a-192c-4a53-940e-da77f8bf0c70.png)

**Comment by OotTheMonk** [comment]
Pulse of Candlehold was coded in an old way, went ahead and changed it to use the multi-select method
![image](https://user-images.githubusercontent.com/77394768/223603867-17a2752a-1928-4d93-b47f-5dd49eaf306c.png)

**Comment by OotTheMonk** [comment]
Codex of frailty fixed too:
![image](https://user-images.githubusercontent.com/77394768/223604513-3aedb9ce-ca6a-4379-b45b-87888eef480f.png)
