### ISSUE TITLE
871977 - Spine Spiring seems to show wrong cards or something is off

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#342]
I opt and saw lace for bloodrot on top and left it on top. Then I load Spine Springing and it drew a codex and show the lace bloodrot.

![Uploading image.png…]()

**Comment by PvtVoid** [comment]
After further test I believe it's drawing the 3rd card on top of the deck and reveal the top 2 card to Spuine Spiring. Death Dealer should always draws first as you can’t interrupt the resolution of DD. Hope it helps

**Comment by OotTheMonk** [comment]
Fixed in 37f7a4a7
