### ISSUE TITLE
871977 - Barbed Undertow.doesn't write in the log which ptich color was choosen

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#343]
![image](https://user-images.githubusercontent.com/26232486/223421528-579af7af-162d-4f8f-812e-ac90ae4509c5.png)

**Comment by OotTheMonk** [comment]
It did when I tried it
![image](https://user-images.githubusercontent.com/77394768/223586903-985cab98-705f-4df6-bf2c-575fb47991aa.png)
