### ISSUE TITLE
872805 - Scout the Periphery show the top card of a deck to the wrong player

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#346]
My opponent played Scour and it showed me a card
![image](https://user-images.githubusercontent.com/26232486/223461977-ccd0d40b-90e1-4296-91d4-d430a5408317.png)

**Comment by OotTheMonk** [comment]
Looks like this happens when you choose to view the opponent's top deck.

**Comment by OotTheMonk** [comment]
Fixed ecfb9dc9
