### ISSUE TITLE
874101 - Conceled Blade didn't give +1 to my opponent attack

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#347]
![image](https://user-images.githubusercontent.com/26232486/223515007-c2118757-c116-4b1e-9b1a-a4b668b7493f.png)

**Comment by OotTheMonk** [comment]
Concealed blade wasn't coded yet, but it _mostly_ is now. You can check the release notes on discord for details on how the current implementation differs from what should happen.

**Comment by PvtVoid** [comment]
Thanks for the fixes! I am not on discord so I was using the news board on the main page and it wasn't showing there. So I thought it was coded :)
