### ISSUE TITLE
874253 - [Bug] Bloodrot Trap only check if a reaction has resolves and not if a reaction has been played or activated

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#348]
No damage and no blood rot token created

![image](https://user-images.githubusercontent.com/26232486/223524444-8370e1b3-ec44-4cf0-b5a6-df4cad8e634f.png)

**Comment by OotTheMonk** [comment]
Fixed in 1fb329b8; should apply to all similar cards that check if an attack reaction was played but it didn't resolve yet.
![image](https://user-images.githubusercontent.com/77394768/224504967-e1185b68-712b-44cd-a87b-5f3a01fe4c20.png)
