### ISSUE TITLE
879196 - Scour the Periphery doesn't tell which topdeck has been checked

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#350]
Maybe adding the log: Player 1 checked the top of their deck / Player 1 checked the top of their opponent's deck 👍🏼 

![image](https://user-images.githubusercontent.com/26232486/223655611-0f9383e3-fb71-4f22-b138-f16d74499e2b.png)

**Comment by OotTheMonk** [comment]
Fixed in 0178aa7f
