### ISSUE TITLE
879196 - [Bug] Ponder + Seek and Destroy doesn't allow me to order the triggers and keep a card for arsenal in the ranger mirror

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#351]
I should be able to reorder the triggers of Ponder + Seek and Destroy to keep a card and an arsenal.

![image](https://user-images.githubusercontent.com/26232486/223656917-a8c11c7b-0b89-4e29-86d5-6808ca05de41.png)
![image](https://user-images.githubusercontent.com/26232486/223656938-d1edfc06-5d4e-462d-93bc-352ae0caebd4.png)

**Comment by PvtVoid** [comment]
879196 - Might be a ponder issue lacking this. Not sure.

It happens later on with Bloodrot + Ponder that couldn't be ordered

![image](https://user-images.githubusercontent.com/26232486/223659101-246d0bb2-0f1d-4ecc-815c-dcac22ffcb35.png)

**Comment by OotTheMonk** [comment]
Fixed in 4ce4868b (seek and destroy)
