### ISSUE TITLE
The Combat Chain button can be uses during reaction step

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#353]
Refer to CR 2.3 7.7 Link Step, Turn Player Priority window to close or continue the chain, if passed it takes us to the 7.8 Close Step and at the end of the close step, the action phase resumes 4.3, where the turn player gains priority again.

It shouldn't be possible to close it during the reaction step. The issue came up with the React-FE as the button to close the combat chain is more visible.

![image](https://user-images.githubusercontent.com/26232486/223735456-f4b44a3c-6348-4a4c-beac-eb64e00ec7d5.png)

**Comment by OotTheMonk** [comment]
Fixed in 1870b7eb
