### ISSUE TITLE
887557 - [QoL] It would be great to have in the chatlog the choice that was done for Be Like Water on-hit. 

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#357]
Currently, we have no information if something was paid and what name was chosen. It would improve clarity if someone isn't focusing on their opponent's resource stack to read the info in the chat log.

![image](https://user-images.githubusercontent.com/26232486/223985952-3bf4a4aa-008a-4cba-a7db-6a03b7364293.png)

**Comment by OotTheMonk** [comment]
Fixed
![image](https://user-images.githubusercontent.com/77394768/224504738-201c8d04-7ec3-45d3-8f9b-52cfbed77288.png)
