### ISSUE TITLE
887995 - [Bug] End Phase with OUT auras isn't properly coded

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#358]
4.4.1. Players do not get priority during the End Phase.

1. You shouldn't be able to use a tunic during the end phase. Either to pay for Bloodrot Pox or anything else.
2. It currently gives back priority to the turn player. So I can decide to let resolve 2 tokens, play my sigil and my opponent can keep playing cards and "get out" of the End Phase. It shouldn't be possible just like it isn't possible to use tunic to pay for Frost Hex. It has to be activated before the beginning of the End Phase.

Feel fres to contact the judge community for clarification

![image](https://user-images.githubusercontent.com/26232486/224020829-e2157eae-8404-4637-ab50-d9e9d5041dde.png)
![image](https://user-images.githubusercontent.com/26232486/224021293-3ce24c93-e508-458e-9080-d118b55c293f.png)

**Comment by OotTheMonk** [comment]
Should be fixed in these revisions
![image](https://user-images.githubusercontent.com/77394768/226234285-7fbc0fbf-e595-4aa0-8707-364c56eb54b9.png)
