### ISSUE TITLE
887995 - [QoL] Shake Down could use a chat log to inform us what was chosen

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#359]
Not a bug, but since the player should be telling what pitch has been chosen it could be some nice information to see. Small QoL
![image](https://user-images.githubusercontent.com/26232486/224022020-3b63334a-53bb-432e-9dfe-1b0822e3c6ad.png)

**Comment by OotTheMonk** [comment]
This is fixed in revision 2ea96d50, but more importantly while fixing it I noticed it was revealing the hand cards prior to giving the option to choose a color. This is a major gameplay problem that has also been resolved.
