### ISSUE TITLE
[Bug] Fatigue Shot Rounding Down instead of Up

### ISSUE THREAD

**Issue by ImPapaya** [Talishar/Talishar#360]
Multiple bug reports of the rounding happening incorrectly - 
823546 
829399 
858523 
In addition to a few reports without game numbers

**Comment by OotTheMonk** [comment]
Fixed! revision 7ff14a8c
![image](https://user-images.githubusercontent.com/77394768/224195758-d3af63c2-8bcd-472a-895c-13f3870be144.png)
