### ISSUE TITLE
Cyclone Roundhouse doesn't banish

### ISSUE THREAD

**Issue by FlyingKiwiNZ** [Talishar/Talishar#370]
Hello,
I played a Spinning Wheel Kick followed by a Cyclone Roundhouse - this should trigger a defending card being randomly banished from each chain link at the beginning of the reaction step. The banish effect didn't occur - in this case it left a That All You Got as the only defending card on a prior chain link which then triggered at the close of the combat chain allowing my opponent to draw a card.

**Comment by OotTheMonk** [comment]
Fixed in 3a39ad70
