### ISSUE TITLE
Mutated Mass calculates * using opponent's pitch zone when played as a block.

### ISSUE THREAD

**Issue by Bonneykins** [Talishar/Talishar#374]

**Comment by Bonneykins** [comment]
<img width="1440" alt="Screen Shot 2023-03-14 at 7 53 40 AM" src="https://user-images.githubusercontent.com/9772010/224884830-815807af-c478-4cd7-93a7-9dbde7693a3e.png">

**Comment by Bonneykins** [comment]
The example above should block for 2 * the num of pitch costs in my pitch zone (0) but instead it is calculating off the opponents (1)

**Comment by Bonneykins** [comment]
Is this related to $mainPlayer being sent as the variable in this line? I can't find an explanation in the code but is the $mainPlayer the player who's turn it is and not necessarily the card owner?

https://github.com/Talishar/Talishar/blob/7004d6b38e15dc27dab940f8fc2b8f746ede1019/CardDictionary.php#L493

**Comment by OotTheMonk** [comment]
@Bonneykins you are right, thank you :)

Fixed in 48a700ad
