### ISSUE TITLE
[ReactUI][Deployment] disable redirects to https://talishar.net from api.talishar.net and legacy.talishar.net

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#376]
I want to start calling https://api.talishar.net/ for all the API stuff for the React FE, so we can swap it over without any fuss later.

Right now calling anything on api.talishar and legacy.talishar does a 302 redirect to talishar.net

It's not the end of the world if we can't do it now but it'll save a headache on timing when we do "flip the switch" - and if necessary revert it.

**Comment by Bluffkin** [comment]
Added conditions to the rewrite rule to trigger the catch all if it doesn't start with api. or legacy.
