### ISSUE TITLE
Concealed Blade Bug

### ISSUE THREAD

**Issue by Calwomack94** [Talishar/Talishar#379]
I started a game with a Talishar equipped as my weapon playing as Arakni. During the game I had used Talishar three times and it had broken. I then attacked with a Surgical Extraction that I had pumped with 2 Concealed Blades. When the on hit trigger resolved it allowed me to choose 2 daggers but only equipped the second dagger I had chosen. It also continued to show the 3 counters from Talishar.

**Comment by OotTheMonk** [comment]
Fixed in b8059914
