### ISSUE TITLE
931078 - [Bug] You can name Head Leads the Tail with HLtT. The text mention **name another card**

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#389]
`When this attacks, **name another card.** Attack action cards with that name have +1{p} this combat chain.`

"You may not name “Head Leads the Tail” as the effect requires you to name another card.

![image](https://user-images.githubusercontent.com/26232486/225245468-49f8970e-3a07-41aa-acb5-a8be178031ee.png)

**Comment by OotTheMonk** [comment]
This is fixed
![image](https://user-images.githubusercontent.com/77394768/228695026-26c678ea-d056-4c20-9443-2356ad199e31.png)
