### ISSUE TITLE
Users can submit chat messages to games w/o an AuthKey. Can impersonate any user in chat.

### ISSUE THREAD

**Issue by sugitime** [Talishar/Talishar#39]
https://github.com/OotTheMonk/FaBOnline/blob/e9f4a0ac8e4348a4ec4465758595f59e8a6dcba6/SubmitChat.php#L6

Its hard to link to the absence of functionality, but when the code is checking for a real game, it should check to make sure the authkey is real too.

We fixed the XSS issues, so this is not really a big risk anymore. Its possible it could result in some bad experiences, but no real security threat to talishar or its users.

**Comment by OotTheMonk** [comment]
Fixed by fab5a738 and 522d3a30
