### ISSUE TITLE
931112 - [Bug] Wander With Purpose should be coded as a trigger to be re-ordered with things like Mask of Momentum

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#390]
Currently, Wander With Purpose doesn't allow you to reorder the hit-trigger

![image](https://user-images.githubusercontent.com/26232486/225246826-773b4068-ee26-499f-aadf-2a4ccdb0525e.png)

**Comment by OotTheMonk** [comment]
This is a duplicate issue. To save time, in the future all hit effects should create a re-orderable trigger instead of doing individually.
