### ISSUE TITLE
931112 - [QoL] Wander With Purpose context hasn't been updated from the Katsu reused code

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#391]
Screenshot of Benji using Katsu ability to his best ability:

![image](https://user-images.githubusercontent.com/26232486/225247088-7471965c-d65c-42fd-b957-2d62fde584f2.png)

**Comment by OotTheMonk** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/77394768/225488561-37d192fe-f7df-45b9-9888-97547d8b012f.png)
