### ISSUE TITLE
931128 - [Bug] Quiver of Rustling Leaves is limited to 1 use, althought it shouldn't be the case

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#392]
The quiver is a blackout and usable once only. While you fix this, you should test this part that I couldn't test with the current code: 

`You can activate Quiver of Rustling Leaves two or more times in a row by holding priority, even if the top card of the deck is an arrow. In this case, the resolution of the first will put the arrow face-up in the arsenal and destroy Quiver of Rustling Leaves, the second and subsequent resolutions will still reveal the top card and attempt to put the card into the arsenal if it’s an arrow.
`
![image](https://user-images.githubusercontent.com/26232486/225247922-c48dc736-5919-4027-a6a9-85e023ebd713.png)

Source: https://fabtcg.com/resources/rules-and-policy-center/release-notes/outsiders/

**Comment by OotTheMonk** [comment]
Fixed in 8274709a
