### ISSUE TITLE
931147 - [Bug] Concealed Blade bring back a dagger I don't have in my inventory

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#393]
### There are 2 bugs with this issue

This is the Katsu deck I used to test: https://fabrary.net/decks/01GRKV82F917AT0F7XJ3MKRHW1

1. When the dagger is destroyed, it is put into the opponent's graveyard. It is neither put into their inventory nor does it continue to exist in the arena. In constructed formats, you only have the cards you’ve registered in your card pool, and they are only in your inventory if you didn’t choose them during the start of the game procedure. If there are no daggers in your inventory, this effect fails.

In this case, I started with my 2 Kodachi (I only have 2 in my decklist) so I shouldn't have any in my inventory to bring back.

2.  The Katsu deck I tested with doesn't have a zephyr needle, but it is an option to bring one back:

![image](https://user-images.githubusercontent.com/26232486/225251353-096714ac-4935-4b34-9bac-2355be80e68f.png)

**Comment by OotTheMonk** [comment]
This is a partially manual effect for now, you should enforce which dagger is left in your inventory.

**Comment by PvtVoid** [comment]
It's quite impossible to enforce it for your opponent without knowing what their deck is. I feel like having it working like that might create a feel bad to players when they learn how it really works and get call out at events 😟

**Comment by OotTheMonk** [comment]
This is why I added the warning to remind players to track their inventory manually:
![image](https://user-images.githubusercontent.com/77394768/225616115-c63ca0df-8d3a-4944-8bc8-115abf9442fd.png)

Would like to change this in the future but for now there are more important issues to improve clarity of the game rules, like for example not allowing players to gain priority during the end phase.

**Comment by PvtVoid** [comment]
So why not keep the issue open until it's fixed? Marking it close sounds more like it'll be forgotten and never checked again 😅
