### ISSUE TITLE
931147 - [Bug] Give and Take doesn't allow you to add multiple action cards on top of your deck if blocked with multiple cards

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#394]
### There are 2 issues with Give and Take

1. Give and Take triggers once each time an action card defends it on the combat chain. If the defending hero declares two or more defending action cards during the defend step, the Give and Take triggers once for each action card. It currently only triggers once.

Source: https://fabtcg.com/resources/rules-and-policy-center/release-notes/outsiders/ + extra info: https://fabtcg.com/articles/rules-reprise-11-outsiders-prevention-among-other-things/

3. Less important, but Give and Take seems to only be checking currently at the defend step. So if an action card is added to the defence during the reaction phase it doesn't trigger, but it should. Like Endless Winter is coded to check continuously.

![image](https://user-images.githubusercontent.com/26232486/225257013-85e566cd-b2ed-4eb8-9bda-6d3239851ab4.png)

**Comment by OotTheMonk** [comment]
Fixed in 69f99dcc
