### ISSUE TITLE
931216 - [Bug] Wreck Havoc shouldn't trigger the card in arsenal when it's turning it face-up

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#395]
Turning a card face-up is not considered revealing the card or putting the card face-up in arsenal. It is simply changing its state from face-down to face-up. So the Azalea player for example shouldn't be given to opportunity to use the Spire Sniping ability.

![image](https://user-images.githubusercontent.com/26232486/225258412-6de40f9e-7258-4128-a7bd-91b07421baaa.png)

Source: https://fabtcg.com/resources/rules-and-policy-center/release-notes/outsiders/

**Comment by OotTheMonk** [comment]
Spire Sniping triggers when it's turned face up, which is what Wreck Havoc does. This seems like it's working as intended to me? If not please clarify.

**Comment by PvtVoid** [comment]
@OotTheMonk It should not trigger when it's turned face up by the opponent Wreak Havoc. I linked the released note already in the previous comment with the info 👍![image](https://user-images.githubusercontent.com/26232486/225526733-5f8acbeb-b80e-4339-b502-5c34e89457be.png)

**Comment by PvtVoid** [comment]
Yeah now that I reread the release notes I think it's fine and I miss read that one 🤔
