### ISSUE TITLE
932166 - [QoL] Widowmaker doesn't show the restriction icon on the opponent d.react when it's preventing the usage

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#396]
![image](https://user-images.githubusercontent.com/26232486/225326630-991f5695-b64a-4356-9a0c-9c45a4c1fa17.png)

**Comment by OotTheMonk** [comment]
This is fixed
![image](https://user-images.githubusercontent.com/77394768/225486879-453cc256-1b16-46c4-adef-8c4edd98059d.png)
