### ISSUE TITLE
Application data being stored in the DOM of the browser. Should probably use session storage on the server.

### ISSUE THREAD

**Issue by sugitime** [Talishar/Talishar#40]
As an example, here is some javascript being created by cat'ing variables from the DOM to create an ajax request:

https://github.com/OotTheMonk/FaBOnline/blob/551c63b5856e7f52907194c9a2329d7832d36714/jsInclude.js#L109

This should probably be stored under $_SESSION and never passed to the end user. Partly because it allows for an attacker to use stolen authKeys, and partly because it increases the impact of any XSS attack in the future.

This is a big architectural change, so lets call this an enhancement and low risk and visit it at some point in the future, if it is deemed that its a change worth making.

**Comment by OotTheMonk** [comment]
This is a good thing to keep in our hat. I have sinced added the auth key in the session, but the session has been unreliable and prone to being reset in the past. That's one benefit to sending the auth key to the client. We could probably switch and it'd be fine most of the time, but rather not take the risk until there's an evident need to do so. Closing as not planned for now.
