### ISSUE TITLE
Somehow feisty locals got an aim counter

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar#422]
![image](https://user-images.githubusercontent.com/77394768/229298620-74b2d6dd-aea5-4bdf-901f-e94c8221b2ce.png)
Game 1051344

**Comment by OotTheMonk** [comment]
I think this got subsequently fixed. I think the issue was in Start.php. I noticed in the gamestate, the HasAimCounter piece of combat chain state was set to "NA". It was also turn 1. When I looked in Start, it was set to 0. I think I might have forgotten to change Start at first when I re-used that piece.

**Comment by LaustinSpayce** [comment]
This bug is still being reported:

https://discord.com/channels/865412150125789214/865423689976774656/1092953708523966505

https://discord.com/channels/865412150125789214/865423689976774656/1092948924597293120

**Comment by OotTheMonk** [comment]
Fixed in f14c9613 (forgot to link issue)
