### ISSUE TITLE
"Add deck to favorites" when creating or joining a game does not work

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#425]
As title:
> Hi again. Just shouting out more things I noticed.
> There seems to be an issue with the decks saving into favorites. Im needing to copy a deck link each time I load the page. Also, the "page back" button, when used from the menu after a game, takes you back into the last game you played even though its over. Repeatedly pressing back any further begins to 'undo' turns.

**Comment by OotTheMonk** [comment]
This is working for me; this might have been another side effect of that login not always happening issue that I just fixed
