### ISSUE TITLE
Manual targeting not being saved in settings

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#427]
Similar to issue #377 it seems that preferences are not being saved in the BE so we need to ch3ck.

> Manual targetting doesn't seem to work on the new client. I turn it on in the settings. Then close the settings and I can't choose the targets. In fact, if I go back to the settings, manual targetting will be turned off again even though I just turned it on.

we’ll need to check the fe is sending the correct value, and that saving and recalling that value is working.

**Comment by OotTheMonk** [comment]
This is working for me, both saving the setting, and manual targeting:
![image](https://user-images.githubusercontent.com/77394768/229543965-bc53a7e3-fe2f-4571-a024-63f5ff267bbe.png)
