### ISSUE TITLE
People should be able to hide their hero when creating game lobby.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#430]
We should think of a solution to hiding heroes for game lobbies.

Maybe in the comp queues the hero could be anonymous?

It's a 50/50 split on people liking the heroes being visible, and not liking it.

The main point of contention is people playing heroes like Kano, or heroes which have a few real bad matchups, find people will choose "easy" matchups into them which is pretty pants.

**Comment by OotTheMonk** [comment]
Personally I really like the idea of making it visible in normal queue and hidden in comp queue. I think that's a good representation of what each queue is meant to be used for.

**Comment by OotTheMonk** [comment]
Fixed in 879d9b3d
No FE changes needed
