### ISSUE TITLE
[Legacy UI] encourage players to use main UI highlighting in options and end game menus

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#435]
Two issues:
- “go to main UI” should be the big shining button in the options menu to encourage people to use the actively maintained new client
- At the end of game should have separate “go to main menu” and “go to legacy client main menu” alongside the other options.

some people really dig the sideboarding page and wanna use that while we improve the main client.

legacy UI should also have on the right have side that it is not being actively maintained, and that they should use the main ui instead. (Let’s see if we can embed the talishar twitter feed so they’ll see the new stuff being added)

**Comment by OotTheMonk** [comment]
![image](https://user-images.githubusercontent.com/77394768/232232139-18efacb8-f2e1-4fba-9463-fb10f57b240b.png)
