### ISSUE TITLE
spark of genius should let you search for cards that cost exactly X, not less than or equal to X

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#448]
https://discord.com/channels/865412150125789214/865423689976774656/1094606392087810181

![0363986D-78FB-4CC4-8568-C1AC24BF73D0](https://user-images.githubusercontent.com/5060535/230775077-e0a4850b-f292-4004-af0e-cee5e4c3aa89.png)

**Comment by OotTheMonk** [comment]
Fixed in 36c7e984
