### ISSUE TITLE
If an aura or permanent is attacking, use the “label” card field to say it is attacking.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#453]
> Current iteration of the UI is practically unusable with  Shimmers of Silver.

+1 counters aren't displayed on auras so you have to remember which ones have them.

Auras stacking mean you have to hope when you select an attacking aura (or select an aura to attack) that it's the right one (if you have 2 auras of the same name but only one has +1 counters).

Thanks 🙂

auras should have atkcounters on them and if a permanent is king an attack you can use the label field everywhere to say it’s the one attacking, if the opponent wants to pop it or interact with it in some way.

**Comment by OotTheMonk** [comment]
Also this:
![image](https://user-images.githubusercontent.com/77394768/232354365-fab1cf16-008d-4549-bceb-a7ee4802b929.png)

**Comment by OotTheMonk** [comment]
The attacker and arsenal one should both be fixed in bb4610fa

**Comment by OotTheMonk** [comment]
Shimmer counters show up in the choose multi window, but not in the field:
![image](https://user-images.githubusercontent.com/77394768/233792804-d24932df-5a80-46f9-ae51-d7050f1884d1.png)

![image](https://user-images.githubusercontent.com/77394768/233792814-8a807b65-b48b-4762-b6b3-2c9c4601d22f.png)

**Comment by OotTheMonk** [comment]
Fixed in 3b8d7a5e
![image](https://user-images.githubusercontent.com/77394768/233792917-92e005b1-b87f-44a4-a204-56ab3dfc53c6.png)
