### ISSUE TITLE
[PWA] Allow multiple computers to be "signed in" to one account

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#457]
Currently, When a user clicks "keep me signed in" - it replaces the token from their previous sign in on another computer. 

Each user should have a list or array of their valid sessions that they have signed in with, and we check the value against that list.

This also had the advantage, we can add "sign out of all devices" if we want them to be allowed to do that.

**Comment by OotTheMonk** [comment]
This might be even easier fixed by just returning the same token if they already had one for all devices

**Comment by OotTheMonk** [comment]
Fixed in 9bd2fe7e, no FE changes needed
