### ISSUE TITLE
Add Playmats to GetCosmetics.php

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#460]
We will also have some patreon playmats and some other ones as well I think. So let's have them returned for now.

Current playmats:
  '0': 'aria',
  '1': 'demonastery',
  '2': 'metrix',
  '3': 'misteria',
  '4': 'pits',
  '5': 'savage',
  '6': 'solana',
  '7': 'volcor'

**Comment by OotTheMonk** [comment]
Fixed in a819bc82
