### ISSUE TITLE
Problem with Cyclone Roundhouse?

### ISSUE THREAD

**Issue by CarlosRoig** [Talishar/Talishar#465]
Hi there,

I attacked with this card after attacking with Spinning Wheel Kick, and the other player had defended in previous chain links with one Equipement in each chain link. It should have been banished 3 equipement, but nothing happened. Not only that. One of the equiopment finished in the banished zone, but my opponent could continue using it and defending with it again.

**Comment by LaustinSpayce** [comment]
> 1441453
> 
> Cyclone Roundhouse combo effect not working. This was a particularly tilting one as I set it up to possibly banish a Drone of Brutality, but the combo effect literally does not work on Cyclone Roundhouse. 

https://discord.com/channels/865412150125789214/865423689976774656/1105432615667892224

**Comment by LaustinSpayce** [comment]
> Cyclone kick didn't banish a card on the previous chainlink 1412229
https://discord.com/channels/865412150125789214/865423689976774656/1104489193046024324

> 1364597 Cyclone Roundhouse is only banishing cards from the latest chain link, not all chain links
https://discord.com/channels/865412150125789214/865423689976774656/1102862336290721824
