### ISSUE TITLE
7.2.5 priority window is missing

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar#467]
This window can be used to take actions that could impact your ability to make blocks. For example:

Sure, this came up the other day. I was Kano, my opponent was rhinar. He played 3 barraging beatdown and then a pack hunt. In the layer step of pack hunt I pitched my final card remaining in hand to activate Kano. I banished tome of aetherweave off the top, and I was going to cast it in 7.2.5 to draw two cards after pack hunt’s intimidate trigger so that I had two cards to block with in the block step to turn off the barraging beat down effects. But without that window in talishar I had to either play tome in response to the intimidate trigger, meaning I’d lose one of the cards to the intimidate, or wait until after blocks, which is too late to use the cards.

**Comment by PvtVoid** [comment]
Fixed with https://github.com/Talishar/Talishar/pull/763/commits/fa687441f94f092989d8542f7f43ecb86f7e97d2
