### ISSUE TITLE
Players who are not signed in can still join public lobbies

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#469]
https://twitter.com/AvidAscension/status/1648374376411152395?s=20

We need to have a hard check on Create and Join game APIs. If they are not logged in and game is public they get booted out, there is a loophole somewhere.

**Comment by LaustinSpayce** [comment]
I just tested on the new UI so we need a login guard on the JoinGame API.

**Comment by LaustinSpayce** [comment]
Related issue

https://github.com/Talishar/Talishar-FE/issues/328

**Comment by OotTheMonk** [comment]
This should be fixed now
