### ISSUE TITLE
Disconnect doesn't make you lose karma. It makes people go lower than 0

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#48]
The code for losing karma is currently commented out. The reason is that people losing karma can go below 0. The code is working I believe, but the math is incorrect and I don't know how to put a lower limit.
 
 https://discord.com/channels/865412150125789214/865423689976774656/1017732312840024085
![image](https://user-images.githubusercontent.com/26232486/191437327-2831582e-93de-4fcc-bbd4-43c3b12aad3b.png)

**Comment by OotTheMonk** [comment]
I believe this is already fixed long back. I just made an update not long ago to change the disconnect penalty from 10 to 2. Closing issue.
