### ISSUE TITLE
Invoking a dragon using ash with ward removes Phantasm from the dragon

### ISSUE THREAD

**Issue by tetsuo-matsumura** [Talishar/Talishar#482]
A player from my country reported an issue with his match as Dromai. 

According to the player, they used **Sand Cover** to give **Ward** to an **Ash**, and then used that **Ash** to play **Invoke Kyloria**. During the attack phase, the opponent attempted to defend with **CnC**, which should have popped the **Kyloria** dragon attack, but it did not.

**Comment by PvtVoid** [comment]
If it's still happening, I'm happy to fix it. Please provide a bug report ID. It helps debug those by saving your gamestate so it's easy to reproduce :)
