### ISSUE TITLE
Dromai missing triggers

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar#487]
Tomeltai
Burn them All
![image](https://user-images.githubusercontent.com/77394768/235805917-3e0e73fe-1ada-40c1-a139-651451e9c521.png)

**Comment by Scapeg** [comment]
same for optimai.

**Comment by PvtVoid** [comment]
Fixed with https://github.com/Talishar/Talishar/pull/772/commits/a16e9c50458d8e2783388ee3fb8d286c14b1d879
![image](https://github.com/Talishar/Talishar/assets/26232486/fd2b7aad-a32d-4ae0-a8da-d3e13cafdf21)
