### ISSUE TITLE
Heatseeker cannot be reordered at end of turn & inconsistencies on wether cards can be reordered between legacy and regular ui

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#496]
Game repro: 1416401

Cannot reorder heatseeker trigger with the other tokens popping despite them all happening at the beginning of the end step.

There are inconsistencies between ordering being allowed on the old UI and the current UI they need to be bought in line.

Start of thread:
https://discord.com/channels/865412150125789214/865423689976774656/1104501589986791540

Opponents also get a chance to reorder triggers so check if this is allowed in the rules, and if not, only the player with priority should be allowed to reorder the triggers:
https://discord.com/channels/865412150125789214/865423689976774656/1104501589986791540

**Comment by OotTheMonk** [comment]
Both these issues are fixed
