### ISSUE TITLE
Pulse wave harpoon someone couldn't select the cards.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#503]
I think it's an issue in the BE with GetNextTurn or something so I'll raise the issue here for now:

https://discord.com/channels/865412150125789214/865423689976774656/1106155504146845737

> 1463613 Playing Pulswave Harpoon on the "new layout" and it autopassed saying that player needed to select items though it was done, resulting in a cancellation each time, turns out switching to "legacy talishar layout" fixed it.

**Comment by OotTheMonk** [comment]
This worked for me when I tried it
![image](https://github.com/Talishar/Talishar/assets/77394768/05dc93be-b09c-4587-b2a4-fc88058ecbf4)
My guess is probably they maybe accidentally hit pass too many times from lag
