### ISSUE TITLE
Total Value Results

### ISSUE THREAD

**Issue by thelazEdog** [Talishar/Talishar#505]
Request to save total value generated and total turn number for each player as part of recorded game results. Make available via API, similar to game results on Fabrary.

e.g. Total value generated = Total Attack Power and Total Defense value of blocked cards
Also with t0 included and not included.

Thanks! :)

**Comment by OotTheMonk** [comment]
What is the goal for this data? Without knowing what it's going to be used for it's hard to justify spending limited dev time on this. Closing as not planned for now unless someone wants to pick this up.
