### ISSUE TITLE
[No Game ID] - Ironsong Pride counters has been reported as not remove the counters from Dawnblade properly

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#508]
Hey, I am judging the Rainbow League this month for Pride month and some bugs were reported from the game. I do not have a game ID as I wasn't playing those games. But if you know about this bug or if it's been reported it would be a quick fix!

![obraz](https://github.com/Talishar/Talishar/assets/26232486/9f0c929f-b0eb-4627-9561-d5d9ee5abd7a)

**Comment by OotTheMonk** [comment]
Fixed in commit 57278c88

Sorry I put the wrong card name in the commit comment because the initial bug report I pulled referred to it by that name, but it is definitely ironsong pride.

![image](https://github.com/Talishar/Talishar/assets/77394768/a6d38b38-5aaf-4f50-bb18-0823b560b99c)
