### ISSUE TITLE
Briar hero ability's logic is technically incorrect.

### ISSUE THREAD

**Issue by dihimono** [Talishar/Talishar#510]
https://github.com/Talishar/Talishar/blob/8b7b025f2c5cbaf6c376e933f16012d7ddd6719c/CharacterAbilities.php#L363

Currently it checks whether there's a embodiment of earth under your control to decide whether to trigger this ability. However this  is not correct and should do some checks like "if this is the first time an attack action has hit", similar to what Katsu ability should do. This would affect cards like tarpit trap.

**Comment by PvtVoid** [comment]
Fixed in https://github.com/lukeputz92/Talishar/commit/ba1e7ebb02df6aab231000679578858bda0f24a2
