### ISSUE TITLE
When rematching, the format is sent to FE as a number and not as a string.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#513]
https://github.com/Talishar/Talishar/blob/571cfa296d07c289eb0cb7fca1fa6b554f087b1c/APIs/GetLobbyInfo.php#L105

When rematching the format is sent to the FE as a number:
<img width="579" alt="image" src="https://github.com/Talishar/Talishar/assets/5060535/ec60f505-c8f5-42d3-a541-003ec31bf8a7">

When you initially join it's a string with the format spelled out:
<img width="558" alt="image" src="https://github.com/Talishar/Talishar/assets/5060535/f65767ab-2872-4213-9efc-a0c0955ee79e">

This only happens when players are rematching.

**Comment by OotTheMonk** [comment]
No longer able to reproduce this one, did you fix it?
