### ISSUE TITLE
Raydn, Duskbane and Helm of Sharpeye

### ISSUE THREAD

**Issue by Kjeldorian** [Talishar/Talishar#521]
Helm of Sharpeye not usable although a card has been charged this turn to trigger Raydn, Duskbane (not on the chain).

Raydn, Duskbane in the arena should be +3 {p} due to the charge condition met. 

Helm of Sharp Eye condition should be met for controlling a weapon with twice the attack power.

**Comment by OotTheMonk** [comment]
Fixed in c066e845
