### ISSUE TITLE
Send original hero to fabrary for stats

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar#523]
When `Levia` or `Levia, Shadowborn Abomination` has transformed into one of her demi-hero forms the hero identifier comes through as `DTD564`.  The challenge then is in FaBrary it's not possible to know if the deck started with the Blitz or CC version of Levia (for deck stats/matchup purposes).

Two options I see (there are surely others)
- [ ] Include the original hero identifier, either by:
  - [ ] Switching back from `DTD564` to the correct Levia identifier before sending
  - [ ] Including an additional field for `demiHeroIdentifier` which is either blank or `DTD564` depending on whether the hero transformed (this also future proofs for additional demi heros?)
- [ ] Include a flag with the results for which format the deck is (CC or Blitz) to then extrapolate hero from

**Comment by manwaring** [comment]
As a workaround, in FaBrary I check the opposing deck hero identifier to determine if it's young or adult, and then set the Levia to be young or adult accordingly.

There are two cases I can think of where this won't work correctly:
- Both decks are Levia and both transform into a demi-hero.  In this scenario it errors out and no results are saved - this could be significant if a lot of Levia mirrors are being played with her becoming more popular.
- It was an open game with an adult vs young hero, in this scenario it records the wrong hero by assuming incorrectly.  This seems very insignificant.

**Comment by OotTheMonk** [comment]
Made a change to add format to the game response; I didn't replace the hero since players might want to know when they flip to one demi-hero or the other. That way you can tell the normal hero and the flipped hero.
![image](https://github.com/Talishar/Talishar/assets/77394768/3bee9c56-fed1-43f6-9742-ebba934be7ef)

This is the format key:
![image](https://github.com/Talishar/Talishar/assets/77394768/1340d8ea-4b97-43a8-8e1b-b796aa8b2b33)

Revision 77c887b7 for reference
