### ISSUE TITLE
Blood Debt is not coded as a trigger - please code it as such

### ISSUE THREAD

**Issue by mclair81** [Talishar/Talishar#528]
Scenario: I'm at 15 life with 9 blood debt and I have a Bloodrot Pox. Because I can't order the Blood Debt triggers to happen before the Pox, I take 2 damage going to 13, and am no longer eligible to flip into Blasmophet, Levia Consumed.

Please let me know if you need more info. Thanks!

**Comment by PvtVoid** [comment]
Outsiders are coded as triggers now 99%. Let me know if this need to be reopen :)

**Comment by PvtVoid** [comment]
I just realized when I closed this issue that I did not understand properly what was request. I did push the fix today. Sorry for the delay :) 
![327206257-97de6eac-87d9-4028-874c-33fda28e2111](https://github.com/Talishar/Talishar/assets/26232486/ee1b022c-f08e-4fe2-8e5f-fc42c2b8fa66)
