### ISSUE TITLE
Equipment destroyed while block stay blocking/on the chain. They shouldn't

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#53]
Easily replicated with Barkbone Strapping

https://discord.com/channels/865412150125789214/865423689976774656/1020432258114531338
`3.5.4d Defending objects are objects that are designated to be defended by a rule or effect (see Rule 7.3.2 and Rule 7.4.2d). Defending objects on a chain link are considered to be defending that chain link until they leave the combat chain. Defending objects are placed on the chain link of the attack they are defending and remain there until the combat chain closes.`

![image](https://user-images.githubusercontent.com/26232486/191439284-0ae8e781-7460-4214-89cd-eeec53475487.png)

**Comment by OotTheMonk** [comment]
Fixed in 213ee4c7
