### ISSUE TITLE
[2132871] - Meep on-hit isn't coded properly. The restriction isn't respected.

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#530]
1st - I don't see an image for the card.
![image](https://github.com/Talishar/Talishar/assets/26232486/91593ef4-a50c-4691-9ee9-ea85a4539a25)

2nd - It can only "steal" items with a cost of 2 or less. Tokens like Gold, Silver and Copper do not have a cost. So they cannot be taken.
From the release notes: https://fabtcg.com/resources/rules-and-policy-center/release-notes/dusk-till-dawn/
Only items controlled by the hero that was hit, and have a cost property with a value of 2 or less can be chosen. If an item does not have a cost (it’s a token, or a card without a cost), it can not be chosen this way.
![image](https://github.com/Talishar/Talishar/assets/26232486/cb703233-e6e4-45ad-aa23-80efb4059cd0)

**Comment by OotTheMonk** [comment]
Actually it looks like the max cost was not implemented either; added both restrictions in 7172362c
