### ISSUE TITLE
Backend Warning after games

### ISSUE THREAD

**Issue by knikov-dev** [Talishar/Talishar#532]
**This is not the first time this is happening for me:**
![image](https://github.com/Talishar/Talishar/assets/8791396/61932084-ebec-4890-9d62-68bac65f4acc)

**After the game finishes it starts popping up. Here is what I get in the console log:**
![image](https://github.com/Talishar/Talishar/assets/8791396/4e22a894-5231-462d-aa1c-9c73fc5d38bf)

**Comment by OotTheMonk** [comment]
Fixed in c9d3dab2
