### ISSUE TITLE
[2182943] - Uzuri kept in memory the card I previously played with her ability

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#539]
See below my hand and the Death Touch going on the board if I skip banishing a card from hand.
I believe you have to make it so you cannot skip the cost of the ability.

![obraz](https://github.com/Talishar/Talishar/assets/26232486/9c941cf4-a2c3-417d-b3f5-f9fc1a19bee0)
![obraz](https://github.com/Talishar/Talishar/assets/26232486/74956e26-5cf6-43d7-a9bf-66db3d0202f9)

**Comment by OotTheMonk** [comment]
Fixed in 7525f42c
