### ISSUE TITLE
[2194097] Took 6 arcane damage and spectral shields consumed without lessening the damage

### ISSUE THREAD

**Issue by Ihatecandles** [Talishar/Talishar#543]
The opponent played an Emeritus scolding on the last turn and I had 2 spectral shields on board. I took 6 and it consumed the spectral shields without reducing the damage by 1 for each spectral shield. There were no effects stopping damage prevention.

**Comment by OotTheMonk** [comment]
I loaded the bug report, but it seemed like you went from 8 to 4 as I would expect with the shields preventing two damage.
