### ISSUE TITLE
[No Game ID] - Blood dept banished should be goign on the stack to allow priority and Levia to play Doomday

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#546]
Here's the context and information. I learned about this rule this morning and saw it's not implemented on Talishar:
![image](https://github.com/Talishar/Talishar/assets/26232486/2ab4bedc-f1e0-4a58-901d-381bec71b4ec)

**Comment by OotTheMonk** [comment]
This was already fixed yesterday I just didn't close this bug report
