### ISSUE TITLE
[2213064] - The update of Dominate from June 2022 hasn't been updated on Talishar (ex. Thump + Pummel interaction)

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#547]
Here's where all the info is: https://fabtcg.com/articles/back-alley-oracle-10-defending-update/

In the scenario, my defence reaction should check if it can legally defence against an attack that now has dominate. And if it can't it should fizzle. The attack has dominate. The defending hero doesn't defend, then during the reaction step, they play a defence reaction from hand and immediately play another defence reaction from hand before the first one resolves. In this case, only the last defence reaction card will resolve and become defending, and the first defence reaction card will fail to resolve because the attack is already defended by a card from hand.

![image](https://github.com/Talishar/Talishar/assets/26232486/1f9bec38-6bba-4b10-bc63-e2216222c0a1)
![image](https://github.com/Talishar/Talishar/assets/26232486/58039957-13d8-4b8b-b3bb-a7e1b060e1ef)

**Comment by OotTheMonk** [comment]
This is fixed 
![image](https://github.com/Talishar/Talishar/assets/77394768/57f9dc9b-5c00-4b04-9ff3-c9b7d000e262)
