### ISSUE TITLE
[2261616] - Feedback - Card Link from Censor hit is missing

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#551]
I would add a card link to censor on-hit to make it easier to find the target in the log.
![obraz](https://github.com/Talishar/Talishar/assets/26232486/65437cd1-618c-4f24-a325-8f5f139bc958)

**Comment by OotTheMonk** [comment]
I don't think we can really give a card link, since Censor chooses a name and not a card. If you arbitrarily choose one pitch value it might seem misleading to players about what Censor does.

**Comment by PvtVoid** [comment]
Makes sense I didn't think about that!
