### ISSUE TITLE
[2262109] - Feedback + Rules correction for Hurl

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#552]
I got a "bad" ending on my previous game killing my opponent with Hurl as he saw nothing that could indicate to him that I paid the additional cost. So I thought I would bring some suggestions to improve the player experience with the card Hurl.

1- I would write a log that tells you if the player has paid the additional cost. At the moment there's nothing, so players have to ask or be careful how much their opponent had left floating.

2- It could be improved by coding the new attack trigger. So that Hurl would have 1 layer (like currently) if the add.cost isn't paid. Otherwise, it would follow the rules of Flesh and Blood and create a new attack layer. It has an inline trigger on paying additional cost and that trigger give hurl a new attack trigger. So opponents who want to do something before they will be hit by a dagger will be able to see the dagger on the stack and act in response to Hurl attack trigger in the attack step.

An example that creates friction right now is with a card like Oasis that targets the dagger for the damage. I can never know which target will be thrown at me, so it's a 50/50 or you need to request the chat + ask the opponent which one will be thrown so you can target it.

Let me know if you need more explanation on the ruling for this. I tried my best to explain it, otherwise if you prefer the help of someone else, feel free to check with the Judge community on JudgeHub 👍🏼 
![obraz](https://github.com/Talishar/Talishar/assets/26232486/93fb5122-078e-4672-b177-149684d827e4)

**Comment by OotTheMonk** [comment]
Added indicator to log explaining when extra resource is paid Fixed in 840e7bdb
