### ISSUE TITLE
[2263753] - Give and Take doesn't have a log about which card that goes back on top of your deck

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#554]
Give and Take put a card from a public zone to the top of the deck and should inform the other player which card it was.
![obraz](https://github.com/Talishar/Talishar/assets/26232486/6b549de3-c81d-426b-b536-785c3c2eb5d9)

**Comment by OotTheMonk** [comment]
Fixed in 7b33cfd7
