### ISSUE TITLE
[2290278] - The target name is showing | when attacking a Dishonored Hero

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#556]
![image](https://github.com/Talishar/Talishar/assets/26232486/63cb2a8b-af6a-433b-aa5e-633d618749f8)

**Comment by PvtVoid** [comment]
Also, you are still using the "clean-up" version of the card from Hoodwill! A bit blurry and low quality.
![image](https://github.com/Talishar/Talishar/assets/26232486/af91c30d-1fec-4af7-8967-18831d98c7ce)

**Comment by OotTheMonk** [comment]
Fixed in c05fcfb0
