### ISSUE TITLE
[Bug] - You are showing games in single player in the spectate area

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#560]
Not sure if it's on purpose, I know they are blocked on the Legacy client.

![image](https://github.com/Talishar/Talishar-FE/assets/26232486/cd4f717a-a941-4d1b-9343-1691f586fd23)
![image](https://github.com/Talishar/Talishar-FE/assets/26232486/4a942629-5f68-4886-aace-bdeec7e6b1b6)

**Comment by OotTheMonk** [comment]
I tried to recreate this issue by creating a new single player game and observing the game list, but I did not see it there. Let me know if there's a way to reproduce this that I missed.

**Comment by OotTheMonk** [comment]
Laustin mentioned this only happens when you play a public game vs. the combat dummy, so I was able to reproduce and fix this.

Revision 7581b81b
