### ISSUE TITLE
Rematch with sideboard doesn't work for Blitz

### ISSUE THREAD

**Issue by knikov-dev** [Talishar/Talishar#562]
When re - matching with sideboard in a private Blitz game, it gives limit of 60 cards and the game cannot be started.

**Comment by LaustinSpayce** [comment]
Related fe ticket https://github.com/Talishar/Talishar-FE/issues/389

**Comment by OotTheMonk** [comment]
I tried replicating this, but was unable to. I did it as a private blitz game against myself, conceded, did full rematch. When I went to the sideboard screen it showed 40 cards requirement and allowed me to start the game as expected. Are there additional steps needed to reproduce this?

**Comment by LaustinSpayce** [comment]
Please try making the game, sideboarding, going into the match, do a turn, refresh the browser, then concede and rematch. (Hence the related ticket)
