### ISSUE TITLE
Decimator Great Axe should allow targeting equipment cards

### ISSUE THREAD

**Issue by j4nw** [Talishar/Talishar#563]
[Decimator Great Axe](https://fabrary.net/cards/decimator-great-axe) should be able to target equipment cards, once the effect is triggered by a non-equipment card. ([mentioned in the DTD release notes](https://fabtcg.com/resources/rules-and-policy-center/release-notes/dusk-till-dawn/))

While I don't have the time and resources to get involved in building the client, testing the change, and submitting a proper pull request, from a quick look at the codebase I believe this is an easy fix?

current:
https://github.com/Talishar/Talishar/blob/b0f3bfc52ecda0da2e152a60fe93d91cbd8fe9b3/CombatChain.php#L242-L247

suggested new:
```php
        $nonEquipBlockingCards = GetChainLinkCards($defPlayer, "", "E");
        if($nonEquipBlockingCards != "") {
          $options = GetChainLinkCards($defPlayer);
          AddCurrentTurnEffect("DTD205", $mainPlayer);
          AddDecisionQueue("CHOOSECOMBATCHAIN", $mainPlayer, $options);
          AddDecisionQueue("HALVEBASEDEFENSE", $defPlayer, "-", 1);
        }
```

Cheers

**Comment by OotTheMonk** [comment]
Fixed in dcaa9a2e
The proposed fix works, thanks :)
(Also tested the interaction with temper to make sure that works and it did)
