### ISSUE TITLE
no scrollbar on permanents zone

### ISSUE THREAD

**Issue by twzoom** [Talishar/Talishar#564]
Currently if you have more than ~4 cards worth of items, allies, or ash you can't use the ones on the right hand side because they are not clickable. They used to flow over the arsenal and you could still click them but now you can't. The only work around is to play in the legacy client. Flowing cards to a second layer, adding a second group to the right of the arsenal, or adding a scroll bar are all ways this could be fixed.

**Comment by LaustinSpayce** [comment]
Hey I'll move this to the FE repo when I am back from vacation - right now the permanents box does have a scroll bar CSS setting enabled, but it's not appearing in chrome. And it's appearing but not usable in Firefox. I've been working on it last week for a few days without making any headway on it so any help on this issue would be very appreciated as it's been very annoying and I'm stuck.

**Comment by OotTheMonk** [comment]
I believe I fixed this, let me know if you're still seeing issues. Screenshot would be helpful if so!
