### ISSUE TITLE
[2625700] - Singe hit me twice instead of once

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#565]
I'm unsure if it happened because I don't have any allies. But I got it for 1 Arcane twice when Kano played Singe from the banish turn 1. He played only 1x singe.

<img width="1280" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/b4889c12-8390-4aa5-9ad7-879cb0c62ed9">

**Comment by KuKetto** [comment]
Yes singe used the default `3: Their Hero + Their Allies` target option. There was no such option as `Their Allies only` so i added that. It should be good now.
