### ISSUE TITLE
[2626478] Souldbond Resolve doesn't seem to appear under my current effects when used

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#566]
I might have missed it, but I couldn't see it to show it'll prevent 1. The card worked properly tho! 👍🏼 
<img width="437" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/3e129222-f093-438d-98c9-8bfe09173185">

**Comment by OotTheMonk** [comment]
It doesn't use the current effects framework, it works in a similar way to for example Zen State token when the condition is met.

**Comment by PvtVoid** [comment]
While I understand that is uses a different framework I don't think it necessarily mean it's right.

You need to indicate a visual effect for the players so they know it's active. I think it would improve the understanding for the wizards I face and Bloodrot pox players, etc..
