### ISSUE TITLE
Barbed Undertow + Bloodrot Pox token

### ISSUE THREAD

**Issue by SwordOfMice** [Talishar/Talishar#568]
In a game, I was hit with an active Barbed Undertow which should prevent me from pitching blue cards. This worked as normal during my turn, but when I went to pay for bloodrot I was allowed to pitch a blue card to avoid damage.

In case it helps, the blue card I pitched at end of turn had been drawn that turn from a Mask of Momentum trigger (i.e. wasn't in my hand when Undertow hit).

**Comment by PvtVoid** [comment]
Fixed with 2797f2adfe12f6f67be86642fa60c4cd762b4ccc
