### ISSUE TITLE
[2691674] - Your arsenal image disapear when you run out of cards in your deck

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#571]
<img width="1146" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/bd8661c4-008a-4ff2-a68b-0fe9774d0787">

**Comment by OotTheMonk** [comment]
This is fixed from working on new Dash code, the issue is before it was sharing the card back image with the deck (which previously was almost always the actual card back)
![image](https://github.com/Talishar/Talishar/assets/77394768/b1e459d6-3211-4b29-ba6d-8d3ab932e0ae)
