### ISSUE TITLE
Vynnset banishes a card from hand when asked for a rematch causing a backend warning.

### ISSUE THREAD

**Issue by KuKetto** [Talishar/Talishar#578]
This is a very conditional and a minor bug. I will look into this later. I just want to leave it here so it won't be forgotten.

Caused by: 
1. Game is conceded when Vynnset is required to banish a card from her hand (the game is conceded before she would banish).
2. A rematch (either quick or with full sideboard) is asked.

This only happens once. So if you decline the rematch but issue a rematch once again the bug won't appear. The game just really want to finish her mandatory trigger one way or another.
![image](https://github.com/Talishar/Talishar/assets/39841262/2f97e506-413a-4642-aa90-48299dcd69ee)

**Comment by OotTheMonk** [comment]
If you see this again, or are able to reproduce, can you add a bug report number and re-open?
