### ISSUE TITLE
Migration to new React Front End

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#58]
Creating an issue for us to discuss and eventually do the migration to the new front end.
I think we can have the FE running on Netlify or AWS or something so we can have CI/CD and all that good stuff to help, plus any CDN would help a lot with loading images too.

My initial proposal is this:

Phase 1, building and beta testing:
https://talishar.net/ working for our users as normal.
https://beta.talishar.net/ having the new front end
https://api.talishar.net/ mirroring talishar.net

Phase 2, when we want the new FE to go live:
https://talishar.net/ serving the new FE
https://api.talishar.net/ serving the API for the new FE
(optional) https://legacy.talishar.net/ because *somebody* will complain the old client does xyz that react client doesn't have.

Because we are making new API/end point specifically for the React FE I think this is a sensible way for us to go about it?

**Comment by LaustinSpayce** [comment]
OK so we've decided on JSON.
Second stage will be to use an express.js server as an API layer between the client and game engine.
Means it's easy to get websockets and stuff like that, we can invoke the php scripts from express.js
Can share resources between express and php using redis

**Comment by OotTheMonk** [comment]
I do believe this one be done :D
