### ISSUE TITLE
Update Nitro Mechanoid

### ISSUE THREAD

**Issue by KuKetto** [Talishar/Talishar#584]
The current UI looks a bit strange and misleading. I think as the EVO set will come out more people will try out Mechanologist heros and the mentioned card itself. I leave this here open as a planned update on the card.

- I think when the cards are transformed all other equipments should be hidden like if you didn't equip them in the first place.
- Based on the text of the card I think you should be able to choose which card you want to banish. Right now this isn't really important but can future proof the card.
- The equipments could be banished similar to the fixed Cyclone Roundhouse and Already Dead card.
- Galvanic Bender should not be an effect if it's banished. Currently when Galvanic Bender is banished Nitro Mechanoid no longer gains +1 attack but the UI still shows it as an active effect.

![Screenshot from 2023-09-21 11-43-42](https://github.com/Talishar/Talishar/assets/39841262/07091614-92fa-4b32-b504-c8da432e59df)

**Comment by KuKetto** [comment]
This is a duplicate of #190
I will mark it as closed

**Comment by LaustinSpayce** [comment]
This ticket has a lot more detail in it though so let's close the other one and keep this one open!

**Comment by scary987** [comment]
I think the proper treatment for nitro mechanoid is to handle it like demi hero which has its own soul, but it is an equipment, and the soul doesnt use the actual zone. There probably should be refactor for any soul, so it doesnt use an additional zone, but cards are put under the card itself instead for future proofing.

**Comment by PvtVoid** [comment]
I think there are only 2 bugs left with this one.

- Galvanic Bender should not be an effect if it's banished. Currently, when Galvanic Bender is banished Nitro Mechanoid no longer gains +1 attack but the UI still shows it as an active effect.

- You can keep attacking with Nitro Mechanoid. The last counter doesn't remove itself - GameID 2807050
