### ISSUE TITLE
"Katsu's ability got to trigger even though I used a tarpit trap earlier in the combat chain on a go again attack"

### ISSUE THREAD

**Issue by KuKetto** [Talishar/Talishar#586]
### Bug report ID number: 2724147

![image](https://github.com/Talishar/Talishar/assets/39841262/d94dd6bc-5f0c-4ec9-b585-587bebd848d8)

I couldn't reproduce the bug report. Please someone rewatch the game's state as I do not have access to that at the time. Thanks!

### My try on reproducing the reported issue:
![Screenshot from 2023-09-21 23-10-14](https://github.com/Talishar/Talishar/assets/39841262/ca3a81d5-0ee9-42e4-b561-1b11b297687c)
![Screenshot from 2023-09-21 23-12-48](https://github.com/Talishar/Talishar/assets/39841262/cb2b7644-1cc7-447d-9d95-569d367c356a)
![Screenshot from 2023-09-21 23-13-09](https://github.com/Talishar/Talishar/assets/39841262/8e23c5c9-f676-40a1-9daf-413dd8b47ea3)
^ The second time an attack action hit Katsu's effect triggered, this is correct as Tarpit Trap only prevents the first one.

**Comment by PvtVoid** [comment]
https://discord.com/channels/865412150125789214/865423689976774656/1197978443095216209
3792150 - https://discord.com/channels/865412150125789214/865423689976774656/1188807280515354684
3759293 - https://discord.com/channels/865412150125789214/865423689976774656/1187274119922851891
And a lot more reports. Should be prioritized in my opinion.

**Comment by PvtVoid** [comment]
Fixed with https://github.com/Talishar/Talishar/pull/786
