### ISSUE TITLE
[Bug] - Fender Bender images and information missing

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#592]
- It attacks for 0
- The image for pitches 2 & 3 are missing
- cost = 0, I didn't need to pitch

<img width="262" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/d37e222b-1590-4d9c-926b-d9a52bd3517e">
<img width="766" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/e2a90f51-c358-421c-b670-674d56b1148e">

**Comment by OotTheMonk** [comment]
This was probably from not uploading the generated card code file, I just re-uploaded it so it should be fixed now. It's working locally for me.

The card images are just because those haven't been spoiled yet.

**Comment by PvtVoid** [comment]
All the images are available in the database :) 

<img width="1062" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/628a0a9e-7731-4736-a1f9-7fa7af6338f4">

**Comment by OotTheMonk** [comment]
It looks like those are in the community data set now so they should be deployed in a few minutes :) 
![image](https://github.com/Talishar/Talishar/assets/77394768/28e9bf6e-8cfe-4687-925b-bb464295a9c6)
