### ISSUE TITLE
Heavy Artillery is partially manual

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar#595]
Ideally we could enforce the block restriction
![image](https://github.com/Talishar/Talishar/assets/77394768/f5d68b34-90ed-4c0c-8e3f-22de8c40bf3b)

**Comment by KuKetto** [comment]
I'm doing restrictions on #588
I think I can implement this when EVO is finished and I return to that branch

**Comment by PvtVoid** [comment]
Fixed in https://github.com/Talishar/Talishar/pull/634/commits/6b392a48429cb72483f67807cbeaf5456a403ff2

<img width="1280" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/af03797a-a29b-4e7d-a7ad-d3d6880272db">
