### ISSUE TITLE
[2751806] - Nitro Mechanoid banish "image" of itself instead of the items/equipments in the banish zone

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#601]
A bit more relevant now with Blessing, Heist, etc... To get them back on the board :)

<img width="1280" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/eb5689ba-0a87-4651-8464-69991cd3bd25">

**Comment by OotTheMonk** [comment]
Duplicate of #584
