### ISSUE TITLE
[Feature] - Make Pulsewave Harpoon automatically reveal the hand if NumBoost >= NumCardsHand

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#602]
<img width="855" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/c6a5dda5-5e79-4ad4-abb8-b33475ea184f">

**Comment by OotTheMonk** [comment]
I think this could be confusing for that player wondering why one of their cards just suddenly appeared blocking. This gives them a chance to orient themselves to the effect. I think just automatically showing their whole hand when applicable might make them think they always have to show it, which could teach them the wrong rules. Even though it takes a little more effort I think it's better to have them click the cards in this case. If a lot of people feel similarly and don't think it would be confusing to newer players we could revisit.
