### ISSUE TITLE
[2752025] - Your equipment doesn't go under Nitro Mechanoid and can still be activated

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#603]
I transform into Nitro Mechanoid and I could still activate my Achilles.
<img width="1280" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/8e1f7e5d-a0e8-4407-9396-9dd34a379376">

**Comment by OotTheMonk** [comment]
Duplicate of #584
