### ISSUE TITLE
[2753772] Genesis issue

### ISSUE THREAD

**Issue by Bilanad** [Talishar/Talishar#605]
At the start of turn Genesis triggers but we don't see any pop-up about the trigger so often we skip it. There are only the highlighted cards in hand.
![Annotation 2023-09-25 175056](https://github.com/Talishar/Talishar/assets/146014682/a7a46c23-8f8d-4c75-8a95-b2782de41946)

**Comment by OotTheMonk** [comment]
Fixed in 3aaadc5b5

![image](https://github.com/Talishar/Talishar/assets/77394768/c033f323-9622-46dc-9beb-2968d88288fa)
