### ISSUE TITLE
[2759707] - Data Link + Data Through Data information are missing hover images.

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#607]
<img width="585" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/5b8ef531-aec3-4414-9ad8-c9160288cba6">

**Comment by OotTheMonk** [comment]
You should clear your cache and try it again; I just checked the image, it is there. But if you tried to load it before, it will cache the "unloadedness" on your browser

**Comment by PvtVoid** [comment]
Even if I cleared my cache it is still happening @OotTheMonk! And I see it's happening with more cards and more people on the discord.
<img width="989" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/aa315c91-2b70-4a55-b407-b5de943c198f">
