### ISSUE TITLE
[2759707] - Cogwerx Base Head allows me to search for any action cards in my graveyard instead of only Attack Action cards

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#608]
<img width="1280" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/67abdef2-b34c-4c8c-bafd-d074d7c505af">

**Comment by PvtVoid** [comment]
@KuKetto I believe this is for you :)

**Comment by KuKetto** [comment]
Yes, there is no restriction on that. You should be able to search for any card even instants and reactions. Whoops, I will fix that today. Thanks for reporting that.
