### ISSUE TITLE
[Feedback] - Open Format appears as livinglegendscc on the side. 

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#610]
Some artifacts of the past I believe. I would either make 2x differents queue or simply make it Open Format at both location :) 
<img width="764" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/ef732365-0532-4b60-b402-db809d474b39">

**Comment by OotTheMonk** [comment]
Fixed in 81a46a09
