### ISSUE TITLE
Mindfield intellect modifier should be in an aura intellect modifier function

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar#618]
![image](https://github.com/Talishar/Talishar/assets/77394768/75f3ecd9-5a9d-4a36-ae92-e2f14bf38343)

**Comment by PvtVoid** [comment]
What is the need why this one would need to be an aura intellect modifier and not Stamp Authority? Curious to know what I could've improve 👍🏼

**Comment by OotTheMonk** [comment]
Stamp Authority should too, I didn't notice that one, I was just looking at
the diff

**Comment by OotTheMonk** [comment]
Fixed in cfb19e59f
