### ISSUE TITLE
[2782509] - Cogwerx arms played at instant speed do not give +1 to my next attack. I have to play it as an action for it to gain the +1

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#624]
<img width="1280" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/f44df7a6-b892-495f-b157-dcdc7e4e0c13">
<img width="1280" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/397a2530-3a55-4b7d-8061-f9e7a3b59c2d">
<img width="1280" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/869b6b1b-a4f8-46bb-9209-70642b01e483">

**Comment by KuKetto** [comment]
I think I know what the issue is here. I can fix that but you can do it also if you want to.
In `AddCurrentTurnEffectNextAttack` it only adds the effect if the first layer is an attack action. You just need to remove that attack action check.

**Comment by OotTheMonk** [comment]
I made the change suggested by @KuKetto which fixes the issue, thanks! Revision 272f9e4ab
