### ISSUE TITLE
Diadem should trigger even when the destroyed permanent is not destroyed by the ward itself

### ISSUE THREAD

**Issue by KuKetto** [Talishar/Talishar#631]
When a permanent (ally) with ward is targeted by the opponent hero and destroyed, Diadem should trigger.
![image](https://github.com/Talishar/Talishar/assets/39841262/cdb99df6-bbec-4b68-9e21-97d13ebc260b)

**Comment by PvtVoid** [comment]
Fixed https://github.com/Talishar/Talishar/pull/636/commits/43ddcce97d353d1f9173719fec908e7cd384bb5a
