### ISSUE TITLE
Add New Stats - Ressource Left / Overpitch on the end of game stats

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#64]
https://discord.com/channels/865412150125789214/971928581267664936/1021877202784104498

**Comment by OotTheMonk** [comment]
This is the rationale from the discord post; seems like a good idea:
![image](https://user-images.githubusercontent.com/77394768/222606215-e46e2c1c-5d10-4e24-9272-514b1a58ed1e.png)

**Comment by OotTheMonk** [comment]
Fixed in c06f080f (also FE change)

**Comment by OotTheMonk** [comment]
FE commit:
![image](https://user-images.githubusercontent.com/77394768/235354315-16a84128-6028-4736-8514-c38984b764f8.png)
