### ISSUE TITLE
Spectator view reveals top of Dash I/O deck

### ISSUE THREAD

**Issue by paulryanclark** [Talishar/Talishar#657]
As a spectator, I can see top of Dash I/O’s deck. This information should not be exposed to spectators and could be used to cheat. 

![IMG_5872](https://github.com/Talishar/Talishar/assets/6261622/0b29bed0-6860-4fb6-8237-e1bcb590fc0e)

**Comment by OotTheMonk** [comment]
Fixed in 89917b60a
