### ISSUE TITLE
Adaptive Plating

### ISSUE THREAD

**Issue by LegoWaffle** [Talishar/Talishar#660]
When starting a game with multiple Adaptive Platings you are unable to equip them to seperate slots, instead they both occupy the same equipment slot
![image](https://github.com/Talishar/Talishar/assets/39611896/c03ce84e-dddd-41c7-b4f6-02ea11a517b4)

**Comment by OotTheMonk** [comment]
Change legs to None equipped then at start game it should prompt you
separately where to put each one

**Comment by LegoWaffle** [comment]
Awesome, after some fidgeting with that menu i was able to eventually get both equipped. thanks!

**Comment by davekerr95** [comment]
Closing this as no longer required.
