### ISSUE TITLE
Already dead doesnt work all the way

### ISSUE THREAD

**Issue by Jabader1** [Talishar/Talishar#661]
already dead doesnt let you banish a defending card on the chain link prior

**Comment by PvtVoid** [comment]
Similarities with https://github.com/Talishar/Talishar/issues/245

**Comment by PvtVoid** [comment]
3897117 - https://discord.com/channels/865412150125789214/865423689976774656/1193268501696229577
![image](https://github.com/Talishar/Talishar/assets/26232486/30f70019-5fb4-4776-aaf6-6b196dd63c79)

**Comment by PvtVoid** [comment]
Fixed with https://github.com/Talishar/Talishar/pull/762
