### ISSUE TITLE
Nitro mechanoid cant use adaptive plating to transform

### ISSUE THREAD

**Issue by ZacharyCauchi** [Talishar/Talishar#671]
Nitro mechanoid won't transform if one of your equipment pieces is adaptive plating.

This is supposed to work, since the modular keyword gives adaptive plating the relevant subtype

![nitrobug-2](https://github.com/Talishar/Talishar/assets/27774340/1e6c2550-d760-4c1c-8acc-46b9b8cea45a)
![nitrobug-1](https://github.com/Talishar/Talishar/assets/27774340/a00ba768-a4ec-409e-b3ca-c490bbf1937c)

**Comment by OotTheMonk** [comment]
Fixed in commit db75f4ca1
