### ISSUE TITLE
[Bug] Point the Tip locked from taking any action.

### ISSUE THREAD

**Issue by BaronBurrito** [Talishar/Talishar#706]
If you don't have a face up arrow in arsenal, you cannot discard (like with the affect of Codex of Frailty) Point the Tip or use it to pay for Enlightened Strike.

**Comment by PvtVoid** [comment]
Fixed with https://github.com/Talishar/Talishar/pull/709/commits/d9834527cf9ff84cfd76f6eb3ec54b66e9e1c1f7. It should be live alter today.
