### ISSUE TITLE
[Bug] - Clash results have multiple bugs

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#721]
3998348 - https://discord.com/channels/865412150125789214/865423689976774656/1197258706644111391
4005326 - https://discord.com/channels/865412150125789214/865423689976774656/1197511976235053126

**Comment by PvtVoid** [comment]
More Clash results being wrong and bugged:
4010320 - https://discord.com/channels/865412150125789214/865423689976774656/1197645645390028892

**Comment by PvtVoid** [comment]
4021931 - https://discord.com/channels/865412150125789214/865423689976774656/1197988504634929262

**Comment by OotTheMonk** [comment]
I haven't checked all of these, but I made two particular fixes that should address some of the common themes I have seen reported (Victor re-clashes not working when Victor wins, one player sometimes winning what should be ties):
![image](https://github.com/Talishar/Talishar/assets/77394768/fc691db1-00de-4a8e-accf-05a0ac3b3b15)
bb6c7191b
2e44172d8
