### ISSUE TITLE
Trounce + Victor is bugged

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar#736]
4149162 - Opponent Victor blocked with Trounce and Clash with Vigor, didn't win both trounce clashes, did win the clash with vigor clash, but then got 3 vigor tokens

**Comment by OotTheMonk** [comment]
I think this one is working as expected. I blocked with both the cards, won both clashes (after the victor redo), and ended up with all the expected tokens. Possibly some confusion is that Wallop got revealed once by the clash of vigor, and also once with trounce, which gives two extra vigor tokens. I suspect that's where the confusion came in.
![image](https://github.com/Talishar/Talishar/assets/77394768/725b9492-4120-4c69-bb8c-0f9066f73074)

**Comment by PvtVoid** [comment]
Here's a new report that I believe when I tried to undo and do it again. It still doesn't work 100% as expected https://discord.com/channels/865412150125789214/865423689976774656/1202553497908936734

**Comment by PvtVoid** [comment]
Two more: https://discord.com/channels/865412150125789214/865423689976774656/1202627726972948480

https://discord.com/channels/865412150125789214/865423689976774656/1202683555113738240

**Comment by OotTheMonk** [comment]
Fixed in 6efbc21ba
Implemented a new way of tracking the winner by encoding it in the card ID, instead of trying to use the DQ vars. Repeated workflow from bug report and it worked as expected -- trounce failed at first, then succeeded after redo and awarded the tokens.
