### ISSUE TITLE
Fix the "hero dodging issue" 	

### ISSUE THREAD

**Issue by Tchamber5** [Talishar/Talishar#74]
9/5

I think reputation should decrease from leaving a lobby as well. Not as much as from leaving a game but e.g. half or third of that. I also had some frustrating experience with lobby leavers

Mentions: 2	

https://discord.com/channels/865412150125789214/971928581267664936/1016437435363770479

**Comment by OotTheMonk** [comment]
There was at least a partial fix to this by introducing a karma penalty for dodging matches in competitive queue. Haven't heard nearly as many complaints about this since that was added. Closing this issue as fixed for now until we hear more about it.
