### ISSUE TITLE
Blasmophet, the Soul Harvester's attack and banish of a 6+ attack is not triggerring Levia's hero ability

### ISSUE THREAD

**Issue by greysv1** [Talishar/Talishar#777]
playing as Levia, just banished a red Endless Maw from my hand with Blasmophet ally's attack, but it didn't turn blood debt off.

**Comment by PvtVoid** [comment]
Hey @greysv1, do you have a bug report ID please?

**Comment by greysv1** [comment]
> Hey @greysv1, do you have a bug report ID please?

Please tell me where I can submit one. There are no clear instructions.

**Comment by PvtVoid** [comment]
When a bug happens you can click Report Bug in the menu! It’ll give you the ID 🙂

**Comment by greysv1** [comment]
> When a bug happens you can click Report Bug in the menu! It’ll give you the ID 🙂
> […](#)
> On Feb 12, 2024 at 19:11 +0100, greysv1 ***@***.***>, wrote: > Hey @greysv1, do you have a bug report ID please? Please tell me where I can submit one. There are no clear instructions. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Oh okay, thanks! I'll try recreate it and submit.

**Comment by PvtVoid** [comment]
Hey, I'll close the issue as it seems ok and inactive. If it happens again, provide the bug report ID and it'll be a pleasure to fix :)
