### ISSUE TITLE
4475445 - Vile Inquisition is not correctly giving player opportunity to target themselves, only auto targeting opponent with no player selection

### ISSUE THREAD

**Issue by Bonneykins** [Talishar/Talishar#789]
https://github.com/Talishar/Talishar/blob/cc56d8011527eb1ddc782dffa5e10accd8d467bc/CardDictionaries/DuskTillDawn/DTDShared.php#L375-L384

**Comment by PvtVoid** [comment]
Hey @Bonneykins, you can target yourself if you turn on the Manual Targeting option. It will go in the else and let you Target_Yourself. It's used for a lot of cards that care about this, but also allow us to shortcut the 95% of the time when it's not needed :) I open it helps, let me know if there's an issue with that!
![image](https://github.com/Talishar/Talishar/assets/26232486/ce95cbed-bb10-41cc-8b19-bdf938f77397)

**Comment by Bonneykins** [comment]
@PvtVoid - my apologies. Thanks for pointing that out for me. Best work to do is no work to do :)
