### ISSUE TITLE
4725883 Mask of Many Faces doesn't seem to work with Crouching Tiger + Open the Center

### ISSUE THREAD

**Issue by n21lv** [Talishar/Talishar#806]
**Description**
Mask of Many Faces doesn't seem to give Crouching Tiger an additional name when used beforehand, thus failing to enable the combo effect.

**Steps to reproduce**
1. Play as Benji
2. Have *Mask of Many Faces*, *Vest of the First Fist*, *Tearing Shuko* and *Pouncing Paws* equipped
3. Have *Bittering Thorns (red)*, a *Salt the Wound*, and a card to pay for the Bittering Thorns in hand
4. Have *Open the Center (red)* in arsenal
5. Play *Bittering Thorns (red)*
6. Opponent must fully block it
7. When you receive priority, activate the abilities of *Tearing Shuko*, *Pouncing Paws*. Hold priority
8. Activate the ability of *Mask of Many Faces* and choose "Head Jab" as the name
9. Play the Crouching Tiger from your hand. Opponent must not block it
10. *Vest of the First Fist* triggers
11. Choose to break *Vest of the First Fist* and gain {r}{r}
12. Use the newly gained resource points to play *Open the Center (red)* from your arsenal
13. Notice that *Open the Center (red)* doesn't gain go again and dominate, but does gain +1 from Benji's ability

**Comment by PvtVoid** [comment]
Hey @n21lv, thanks for the report! I just pushed the fix. It should be live with the next server update. https://github.com/Talishar/Talishar/pull/805/commits/a9b85372c1553b06a3a63cb40e524f31a36a4e50
