### ISSUE TITLE
Leave No Witnesses doesn't banish from Arsenal?

### ISSUE THREAD

**Issue by afretfuldisaster** [Talishar/Talishar#807]
Playing as Fai, opponent is playing as Uzuri. They hit me with a Leave No Witnesses and my arsenal was a Tome of Firebrand. The top card of my deck got banished but my arsenal did not. Later on the same issue occurred with a new and different arsenal card.

**Comment by PvtVoid** [comment]
Hey, Leave no Witnesses banish from arsenal is optional. It says "up to 1". Maybe the Uzuri player didn't want to free your arsenal and pass on the window to banish from arsenal? Does it makes sense?
![image](https://github.com/Talishar/Talishar/assets/26232486/82b89a30-10ba-4f8e-9572-b9362d20fdfc)
