### ISSUE TITLE
[5447063] - Blood Debt should be an orderable trigger

### ISSUE THREAD

**Issue by BaronBurrito** [Talishar/Talishar#826]
You are unable to reorder where Blood Debt occurs on end step meaning that if you ever have a Bloodrot Pox token and are at 14 as Levia it will always trigger before you take Blood Debt and you are unable to reach Blasmophet Consumed.

**Comment by PvtVoid** [comment]
Hey @BaronBurrito, are you able to provide a bug report ID? You get one when you click "Report Bug" in the menu.
![obraz](https://github.com/Talishar/Talishar/assets/26232486/6ca8b9a8-fad2-449b-a859-d98f2f84202b)

I believe if you have the "Always Hold Priority" setting, it should be available to reorder. Can you confirm if that fixes it?

**Comment by BaronBurrito** [comment]
Hi. 5447063 is my bug report ID. I have a link to a video [here](https://drive.google.com/file/d/1YuYBlcsU2J91Jzs_yxfSxiluIONPANHB/view?usp=sharing). It's not included in the video but I double checked that Always Hold Priority was on right after the video finished.

**Comment by PvtVoid** [comment]
Should be fix! Sorry it took so much time, I forgot about it :) ![image](https://github.com/Talishar/Talishar/assets/26232486/97de6eac-87d9-4028-874c-33fda28e2111)

**Comment by BaronBurrito** [comment]
No problem. Just glad to see this as a feature. Thanks!
