### ISSUE TITLE
Issues with Fabricate

### ISSUE THREAD

**Issue by SlimyBlob** [Talishar/Talishar#844]
This mode on Fabricate don't work like it should: "Equip a base equipment with Proto in its name from your inventory".
You get the option to pick any proto base equipment, but in CC and Blitz you should only be able to pick cards in your inventory.
You are able to override existing equipment in the client, but this is not a legal play. The equipment should be broken before being able to equip.

**Comment by PvtVoid** [comment]
Thanks @SlimyBlob, should all be fixed with this push I just did: https://github.com/Talishar/Talishar/commit/0c22e66e4692af66e19dad4b3ff7552915131e7a
