### ISSUE TITLE
2820490 - Barbed Castaway using the same mode twice in a turn

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#845]

**Comment by n21lv** [comment]
Just tested how Micro-Processor (EVR070) abilities work in a single-player game, and they are being processed correctly, removing the used-up options from the prompt when item is activated.

Then tested Barbed Castaway in another single-player game, and both options are available after using either of them.

**Comment by PvtVoid** [comment]
Fixed with 0f374fc7c9c341f9c19ac8b54809c9428029de42
