### ISSUE TITLE
Leave No Witnesses doesn't banish from Arsenal

### ISSUE THREAD

**Issue by plamen-kutinchev** [Talishar/Talishar#849]
I don't get any prompt or anything, it just auto banishes the top card only and leaves the arsenal. It is suppose to banish from arsenal also: https://www.tcgplayer.com/product/453418/flesh-and-blood-tcg-dynasty-leave-no-witnesses?Language=English

**Comment by PvtVoid** [comment]
Should be fixed, thanks!
