### ISSUE TITLE
Brute equipment dice roll

### ISSUE THREAD

**Issue by komilll** [Talishar/Talishar#876]
I think there are 2 bugs:
1) When rolling for "Scabskin Leathers" you can activate "Barkbone Strapping" instant ability. In that case, you will roll for barkbone and then re-roll original dice throw for scabskin's which doesn't seem correct, unless I'm missing some judging here.
2) Whenever "1" comes up using scabskin's or barkone, "Gambler's Gloves" doesn't seem to change the result. I think I got "1" about 10-15 times and used gloves but it has never changed the result. Obviously, it might be my luck but it seems improbable that it have never rolled higher results. However, for every other number, gloves re-roll correctly, giving higher or lower results.

**Comment by BaronBurrito** [comment]
#1 was definitely a problem and my newest pull request should fix it. The second might legitimately be extreme bad luck. Talishar's random number generation is valid in my experience and investigations of the code.
