### ISSUE TITLE
Multiple instances of Adaptive Plating

### ISSUE THREAD

**Issue by dokempf** [Talishar/Talishar#879]
Blocking with two separate Adaptive Platings on a single attack results in only one of them being destroyed:

![Screenshot from 2024-07-15 22-39-09](https://github.com/user-attachments/assets/9260b8ad-5c8d-4937-943c-1b31a480c33a)
![Screenshot from 2024-07-15 22-39-19](https://github.com/user-attachments/assets/16bb21c0-d797-492b-b703-a432c0fdb9ff)

FWIW, I galvanized both.

**Comment by PvtVoid** [comment]
Thanks, should be fixed!
