### ISSUE TITLE
Chatlog / GameLog Summary

### ISSUE THREAD

**Issue by Tchamber5** [Talishar/Talishar#91]
9/9

Mentions: 1	

https://discord.com/channels/865412150125789214/971928581267664936/1017443023770091643

![image](https://user-images.githubusercontent.com/22121180/196743594-1a73fa50-b2a5-4a93-8d41-27a1a5736987.png)

**Comment by OotTheMonk** [comment]
I think this should be mostly covered by the replays functionality once it's released

**Comment by OotTheMonk** [comment]
Closing this since it's already linked to replays
