### ISSUE TITLE
Unable to reorder Eloquence triggered ability

### ISSUE THREAD

**Issue by NavrasK** [Talishar/Talishar#974]
I've been playtesting Vynnset and noticed a changed behaviour which makes it impossible to perform certain combos in the hero.  When playing a Shadow non-attack action while I control an Eloquence token I used to be able to reorder the trigger from Vynnset to resolve before Eloquence, giving me the opportunity to pay 1 life and play Funeral Moon or Requiem of the Damned at instant speed, triggering Eloquence again to gain an action point (interaction is confirmed in DTD release notes for Eloquence).  Some abilities are still able to be reordered on the stack, such as Runechants and Malefic Incantation, but no matter what priority settings I've used I cannot rearrange the Vynnset trigger with Eloquence and these lines haven't worked since Rosetta was released.

**Comment by PvtVoid** [comment]
Hello, should be fixed as of a week ago or so. Thank you!
